-- Batch 432 - 500 records
BEGIN TRANSACTION;

INSERT OR REPLACE INTO bins (bin, brand, type, category, issuer, country, bank_phone, bank_url) VALUES
    ('480838', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480839', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480840', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480841', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480842', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480843', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480844', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480845', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480846', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480847', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480848', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480849', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480850', 'VISA', 'CREDIT', 'PURCHASING', 'CITIBANK - COLOMBIA', 'Colombia', NULL, NULL),
    ('480851', 'VISA', 'CREDIT', 'PURCHASING WITH FLEET', 'BANK OF AMERICA, NATIONAL ASSOCIATION', 'CANADA', NULL, 'https://www.bankofamerica.com'),
    ('480852', 'VISA', 'CREDIT', 'PURCHASING', 'CITIBANK - COLOMBIA', 'Colombia', NULL, NULL),
    ('480853', 'VISA', 'CREDIT', 'PURCHASING', 'BANCO NACIONAL DE COSTA RICA', 'Costa Rica', '(506) 2212-2000', 'www.bncr.fi.cr'),
    ('480854', 'VISA', 'CREDIT', 'PURCHASING', 'BANCO DE RESERVAS DE LA REPUBLICA DOMINICANA', 'Dominican Republic', '809 960 2121', 'www.banreservas.com'),
    ('480855', 'VISA', 'CREDIT', 'PURCHASING', 'ICICI BANK, LTD.', 'India', '1860 120 7777', 'www.icicibank.com'),
    ('480856', 'VISA', 'DEBIT', 'PURCHASING WITH FLEET', 'ASOCIACION POPULAR DE AHORROS Y PRESTAMOS', 'DOMINICAN REPUBLIC', '809.687.APAP (2727)', 'http://www.apap.com.do'),
    ('480857', 'VISA', 'CREDIT', 'PURCHASING', 'VISA ARGENTINA, S.A.', 'Argentina', '0800-666-0171', 'www.visa.com.ar/'),
    ('480858', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480859', 'VISA', 'CREDIT', 'PURCHASING', 'NUEVO BANCO COMERCIAL, S.A.', 'Uruguay', NULL, NULL),
    ('480860', 'VISA', 'DEBIT', 'PURCHASING', 'VISA ARGENTINA, S.A.', 'Argentina', '0800-666-0171', 'www.visa.com.ar/'),
    ('480861', 'VISA', 'CREDIT', 'PURCHASING', 'BANCO MULTIPLE SANTA CRUZ, S.A.', 'Dominican Republic', '1-809-726-2222', 'www.bsc.com.do'),
    ('480862', 'VISA', 'CREDIT', 'PURCHASING', 'TARJETAS UNISOLUCIONES S.A. DE C.V.', 'Mexico', NULL, NULL),
    ('480863', 'VISA', 'CREDIT', 'PURCHASING WITH FLEET', 'INTL HDQTRS-CENTER OWNED', 'UNITED STATES', NULL, NULL),
    ('480864', 'VISA', 'CREDIT', 'PURCHASING WITH FLEET', 'THE BANCORP BANK, NATIONAL ASSOCIATION', 'UNITED STATES', NULL, NULL),
    ('480865', 'VISA', 'CREDIT', 'PURCHASING', 'P.T. BANK CIMB NIAGA TBK.', 'INDONESIA', '+621500800', 'https://www.cimbniaga.co.id'),
    ('480866', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480867', 'VISA', 'CREDIT', 'PURCHASING', 'BANCO MULTIPLE CARIBE INTERNACIONAL, S.A.', 'Dominican Republic', '809 378 0505', 'www.bancocaribe.com.do'),
    ('480868', 'VISA', 'CREDIT', 'PURCHASING', 'CITIBANK CANADA', 'Canada', '416-947-5500', 'www.citigroup.com/canada/en/'),
    ('480869', 'VISA', 'DEBIT', 'PREPAID PURCHASING WITH FLEET', 'BANCO PROVINCIA DE TIERRA DEL FUEGO', 'ARGENTINA', '+548109997470', 'http://www.bancotdf.com.ar'),
    ('480870', 'VISA', 'CREDIT', 'PURCHASING', 'EASTERN BANK, LTD.', 'Bangladesh', '+88 09666777325', 'www.ebl.com.bd'),
    ('480871', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480872', 'VISA', 'CREDIT', 'PURCHASING WITH FLEET', 'THE BANCORP BANK, NATIONAL ASSOCIATION', 'UNITED STATES', NULL, NULL),
    ('480873', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480874', 'VISA', 'CREDIT', 'PURCHASING', 'FIRST ABU DHABI BANK PJSC', 'UNITED ARAB EMIRATES', '+971600525500', 'https://www.bankfab.com'),
    ('480875', 'VISA', 'CREDIT', NULL, 'VISA ARGENTINA, S.A.', 'Argentina', '0800-666-0171', 'www.visa.com.ar/'),
    ('480876', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480877', 'VISA', 'CREDIT', 'PURCHASING', 'FIRST ABU DHABI BANK PJSC', 'UNITED ARAB EMIRATES', '+971600525500', 'https://www.bankfab.com'),
    ('480878', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480879', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480880', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480881', 'VISA', 'CREDIT', NULL, 'UNIBANK, LTD.', 'United States', '425-275-9700', 'www.unibankusa.com'),
    ('480882', 'VISA', 'CREDIT', NULL, 'UNIBANK, LTD.', 'United States', '425-275-9700', 'www.unibankusa.com'),
    ('480883', 'VISA', 'CREDIT', 'PURCHASING WITH FLEET', 'FIRSTRAND BANK, LTD.', 'SOUTH AFRICA', NULL, 'http://www.firstrand.co.za'),
    ('480884', 'VISA', 'CREDIT', 'PURCHASING WITH FLEET', 'FIRSTRAND BANK, LTD.', 'SOUTH AFRICA', NULL, 'http://www.firstrand.co.za'),
    ('480885', 'VISA', 'CREDIT', 'PURCHASING WITH FLEET', 'FIRSTRAND BANK, LTD.', 'SOUTH AFRICA', NULL, 'http://www.firstrand.co.za'),
    ('480886', 'VISA', 'CREDIT', 'PURCHASING WITH FLEET', 'FIRSTRAND BANK, LTD.', 'SOUTH AFRICA', NULL, 'http://www.firstrand.co.za'),
    ('480887', 'VISA', 'CREDIT', 'PURCHASING WITH FLEET', 'FIRSTRAND BANK, LTD.', 'SOUTH AFRICA', NULL, 'http://www.firstrand.co.za'),
    ('480888', 'VISA', 'CREDIT', 'PURCHASING WITH FLEET', 'FIRSTRAND BANK, LTD.', 'SOUTH AFRICA', '+27112821808', 'http://www.firstrand.co.za'),
    ('480889', 'VISA', 'CREDIT', 'PURCHASING WITH FLEET', 'FIRSTRAND BANK, LTD.', 'SOUTH AFRICA', '+27112821808', 'http://www.firstrand.co.za'),
    ('480890', 'VISA', 'CREDIT', 'PURCHASING WITH FLEET', 'STATE BANK OF SOUTHERN UTAH', 'UNITED STATES', '+14358652300', 'https://www.sbsu.com'),
    ('480891', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480892', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480893', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480894', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480895', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480896', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480897', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480898', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480899', 'VISA', 'CREDIT', 'PURCHASING', NULL, 'UNITED STATES', NULL, NULL),
    ('480900', 'VISA', 'CREDIT', 'GOLD', 'JYSKE BANK (GIBRALTAR), LTD.', 'GIBRALTAR', '89 89 89 89', 'http://www.jyskebank.gi'),
    ('480901', 'VISA', 'CREDIT', 'CLASSIC', 'JYSKE BANK (GIBRALTAR), LTD.', 'GIBRALTAR', '89 89 89 89', 'http://www.jyskebank.gi'),
    ('480902', 'VISA', 'CREDIT', 'GOLD', 'JYSKE BANK (GIBRALTAR), LTD.', 'GIBRALTAR', '89 89 89 89', 'http://www.jyskebank.gi'),
    ('480903', 'VISA', 'CREDIT', 'CLASSIC', 'JYSKE BANK (GIBRALTAR), LTD.', 'GIBRALTAR', '89 89 89 89', 'http://www.jyskebank.gi'),
    ('480904', 'VISA', 'CREDIT', 'GOLD', 'JYSKE BANK (GIBRALTAR), LTD.', 'GIBRALTAR', '89 89 89 89', 'http://www.jyskebank.gi'),
    ('480905', 'VISA', 'CREDIT', 'CLASSIC', 'JYSKE BANK (GIBRALTAR), LTD.', 'GIBRALTAR', '89 89 89 89', 'http://www.jyskebank.gi'),
    ('480906', 'VISA', 'CREDIT', 'GOLD', 'JYSKE BANK (GIBRALTAR), LTD.', 'GIBRALTAR', '89 89 89 89', 'http://www.jyskebank.gi'),
    ('480907', 'VISA', 'CREDIT', 'CLASSIC', 'JYSKE BANK (GIBRALTAR), LTD.', 'GIBRALTAR', '89 89 89 89', 'http://www.jyskebank.gi'),
    ('480908', 'VISA', 'CREDIT', 'PREMIER', 'JYSKE BANK (GIBRALTAR), LTD.', 'Gibraltar', NULL, 'jyskebank.com/en/units/gibraltar'),
    ('480909', 'VISA', 'CREDIT', 'CLASSIC', 'JYSKE BANK (GIBRALTAR), LTD.', 'GIBRALTAR', '89 89 89 89', 'http://www.jyskebank.gi'),
    ('480910', 'VISA', 'CREDIT', 'GOLD', 'JYSKE BANK (GIBRALTAR), LTD.', 'GIBRALTAR', '89 89 89 89', 'http://www.jyskebank.gi'),
    ('480911', 'VISA', 'CREDIT', 'CLASSIC', 'JYSKE BANK (GIBRALTAR), LTD.', 'GIBRALTAR', '89 89 89 89', 'http://www.jyskebank.gi'),
    ('480912', 'VISA', 'CREDIT', 'GOLD', 'JYSKE BANK (GIBRALTAR), LTD.', 'GIBRALTAR', '89 89 89 89', 'http://www.jyskebank.gi'),
    ('480913', 'VISA', 'CREDIT', 'CLASSIC', 'JYSKE BANK (GIBRALTAR), LTD.', 'GIBRALTAR', '89 89 89 89', 'http://www.jyskebank.gi'),
    ('480914', 'VISA', 'DEBIT', 'GOLD', 'JYSKE BANK (GIBRALTAR), LTD.', 'GIBRALTAR', '89 89 89 89', 'http://www.jyskebank.gi'),
    ('480915', 'VISA', 'CREDIT', 'SIGNATURE', 'BANCO GENERAL, S.A.', 'PANAMA', '+5072066800', 'http://www.banco-general.com'),
    ('480916', 'VISA', 'CREDIT', 'SIGNATURE', 'BANCO DE CHILE', 'CHILE', '+566006373737', 'http://www.bancochile.cl'),
    ('480917', 'VISA', 'DEBIT', 'CHECK CARD', 'CHARLES SCHWAB BANK', 'United States', '1-888-403-9000', 'www.schwabbank.com/'),
    ('480918', 'VISA', 'DEBIT', 'CHECK CARD', 'CHARLES SCHWAB BANK', 'United States', '1-888-403-9000', 'www.schwabbank.com/'),
    ('480919', 'VISA', 'DEBIT', 'CHECK CARD', 'CHARLES SCHWAB BANK', 'United States', '1-888-403-9000', 'www.schwabbank.com/'),
    ('480920', 'VISA', 'DEBIT', 'CHECK CARD', 'CHARLES SCHWAB BANK', 'United States', '1-888-403-9000', 'www.schwabbank.com/'),
    ('480921', 'VISA', 'DEBIT', 'CHECK CARD', 'CHARLES SCHWAB BANK', 'United States', '1-888-403-9000', 'www.schwabbank.com/'),
    ('480922', 'VISA', 'DEBIT', 'CLASSIC', 'INTERNATIONAL BANK OF COMMERCE', 'United States', '(956) 722-7611', 'www.ibc.com'),
    ('480923', 'VISA', 'DEBIT', 'CHECK CARD', 'CHARLES SCHWAB BANK', 'United States', '1-888-403-9000', 'www.schwabbank.com/'),
    ('480924', 'VISA', 'DEBIT', 'PREPAID CLASSIC', 'INTERNATIONAL BANK OF COMMERCE', 'UNITED STATES', '+19567241616', 'https://www.ibc.com'),
    ('480925', 'VISA', 'CREDIT', 'CLASSIC', 'AIB GROUP (UK) PLC', 'United Kingdom', '+44 (0)28 9023 6644', 'aibgb.co.uk'),
    ('480926', 'VISA', 'DEBIT', 'INFINITE', 'MASHREQBANK', 'EGYPT', NULL, 'http://www.mashreqbank.com'),
    ('480927', 'VISA', 'CREDIT', 'CLASSIC', 'BALTIMORE WASHINGTON F.C.U.', 'United States', '410-787-4680', 'baltimorewashingtonfcu.org'),
    ('480928', 'VISA', 'CREDIT', 'SIGNATURE BUSINESS', 'QATAR INTERNATIONAL ISLAMIC BANK', 'QATAR', NULL, 'http://www.qiib.com.qa'),
    ('480929', 'VISA', 'CREDIT', 'CLASSIC', 'THE NATIONAL BANK OF UMM AL-QAIWAIN PSC.', 'UNITED ARAB EMIRATES', NULL, NULL),
    ('480930', 'VISA', 'CREDIT', 'CLASSIC', 'SVENSKA HANDELSBANKEN AB (PUBL)', 'Sweden', '0771-77 88 99', 'www.handelsbanken.se/sv/'),
    ('480931', 'VISA', 'DEBIT', 'BUSINESS', 'TURKIYE IS BANKASI, A.S.', 'IRAQ', NULL, 'http://www.isbank.com.tr'),
    ('480932', 'VISA', 'DEBIT', 'CLASSIC', 'EXCHANGE BANK OF MISSOURI', 'United States', '866-642-4144', 'www.ebmo.com'),
    ('480933', 'VISA', 'DEBIT', 'BUSINESS', 'EXCHANGE BANK OF MISSOURI', 'United States', '866-642-4144', 'www.ebmo.com'),
    ('480934', 'VISA', 'CREDIT', NULL, 'NATIONAL WESTMINSTER BANK PLC', 'United Kingdom', '03457 888 444', 'personalanatwest.com'),
    ('480935', 'VISA', 'CREDIT', 'CLASSIC', 'CREDIMAX B.S.C. (CLOSED)', 'Bahrain', NULL, NULL),
    ('480936', 'VISA', 'DEBIT', 'CHECK CARD', 'CHARLES SCHWAB BANK', 'United States', '1-888-403-9000', 'www.schwabbank.com/'),
    ('480937', 'VISA', 'DEBIT', 'ELECTRON', 'BANCO COOPERATIVO ESPANOL, S.A.', 'SPAIN', '+34902310902', 'http://www.santander.com');

INSERT OR REPLACE INTO bins (bin, brand, type, category, issuer, country, bank_phone, bank_url) VALUES
    ('480938', 'VISA', 'DEBIT', 'CLASSIC', 'JSCB MOSCOW INDUSTRIAL BANK', 'RUSSIA', '8 (800) 100-74-74 1', 'www.minbank.ru/'),
    ('480939', 'VISA', 'CREDIT', NULL, 'SANTANDER BANK POLSKA, S.A.', 'POLAND', '+17153955531', 'http://english.bzwbk.pl'),
    ('480940', 'VISA', 'DEBIT', 'CHECK CARD', 'CHARLES SCHWAB BANK', 'United States', '1-888-403-9000', 'www.schwabbank.com/'),
    ('480941', 'VISA', 'DEBIT', 'CHECK CARD', 'CHARLES SCHWAB BANK', 'United States', '1-888-403-9000', 'www.schwabbank.com/'),
    ('480942', 'VISA', 'CREDIT', 'CLASSIC', 'STANDARD CHARTERED BANK', 'United Arab Emirates', '600 5222 88', 'www.sc.com/ae'),
    ('480943', 'VISA', 'DEBIT', 'ELECTRON', 'BANCO BILBAO VIZCAYA ARGENTARIA S.A. (BBVA)', 'Spain', '913 746 000', 'https://www.bbva.es'),
    ('480944', 'VISA', 'DEBIT', 'ELECTRON', 'COMMERCIAL BANK OF KUWAIT, S.A.K.', 'Kuwait', '1888225', 'www.cbk.com'),
    ('480945', 'VISA', 'DEBIT', 'ELECTRON', 'CAIXABANK, S.A.', 'SPAIN', '+34902110582 / +34934117503', 'http://www.caixabank.com'),
    ('480946', 'VISA', 'CREDIT', 'CLASSIC', 'ALPHA BANK', 'Greece', '210 326 0000', 'www.alpha.gr'),
    ('480947', 'VISA', 'DEBIT', 'ELECTRON', 'ALPHA BANK', 'Greece', '210 326 0000', 'www.alpha.gr'),
    ('480948', 'VISA', 'DEBIT', 'CHECK CARD', 'CHARLES SCHWAB BANK', 'United States', '1-888-403-9000', 'www.schwabbank.com/'),
    ('480949', 'VISA', 'DEBIT', 'CLASSIC', 'PRIORBANK JSCB', 'BELARUS', '+375172899292', 'http://www.priorbank.by'),
    ('480950', 'VISA', 'DEBIT', 'CLASSIC', 'ARK VALLEY CREDIT UNION', 'UNITED STATES', '+16204428210', 'https://arkvalleycu.org'),
    ('480951', 'VISA', 'CREDIT', 'CLASSIC', 'ICBA BANCARD, INC.', 'UNITED STATES', '+18002424770', 'https://www.icba.org'),
    ('480952', 'VISA', 'CREDIT', 'CLASSIC', 'ICBA BANCARD, INC.', 'UNITED STATES', '+18002424770', 'https://www.icba.org'),
    ('480953', 'VISA', 'CREDIT', 'CLASSIC', 'HUMBOLDT BANK', 'United States', NULL, NULL),
    ('480954', 'VISA', 'CREDIT', 'PLATINUM', 'GARDEN STATE F.C.U.', 'United States', '800-713-2274', 'www.gardenstatefcu.org/'),
    ('480955', 'VISA', 'CREDIT', 'PREMIER', 'SANTA BARBARA COUNTY F.C.U.', 'United States', '805.682.3357', 'www.sbcreditunion.com/'),
    ('480956', 'VISA', 'DEBIT', 'CLASSIC', 'HOME FEDERAL BANK', 'United States', '318-629-2265', 'www.hfbla.com'),
    ('480957', 'VISA', 'DEBIT', 'CLASSIC', 'HOME FEDERAL BANK', 'United States', '318-629-2265', 'www.hfbla.com'),
    ('480958', 'VISA', 'DEBIT', 'PREPAID', 'COMMERCE BANCSHARES, INC.', 'UNITED STATES', '+18556591656', 'https://www.commercebank.com'),
    ('480959', 'VISA', 'CREDIT', 'CLASSIC', 'ICBA BANCARD, INC.', 'UNITED STATES', '+18002424770', 'https://www.icba.org'),
    ('480960', 'VISA', 'CREDIT', 'CLASSIC', 'ICBA BANCARD, INC.', 'UNITED STATES', '+18002424770', 'https://www.icba.org'),
    ('480961', 'VISA', 'CREDIT', 'PREMIER', 'GREAT BASIN F.C.U.', 'United States', '(775) 333-4228', 'www.greatbasin.org'),
    ('480962', 'VISA', 'DEBIT', 'CHECK CARD', 'CHARLES SCHWAB BANK', 'United States', '1-888-403-9000', 'www.schwabbank.com/'),
    ('480963', 'VISA', 'DEBIT', 'CHECK CARD', 'CHARLES SCHWAB BANK', 'United States', '1-888-403-9000', 'www.schwabbank.com/'),
    ('480964', 'VISA', 'DEBIT', 'CHECK CARD', 'CHARLES SCHWAB BANK', 'United States', '1-888-403-9000', 'www.schwabbank.com/'),
    ('480965', 'VISA', 'DEBIT', 'CLASSIC', 'ZIONS FIRST NATIONAL BANK', 'United States', NULL, NULL),
    ('480966', 'VISA', 'CREDIT', 'CLASSIC', 'FIRST BANK & TRUST CO.', 'UNITED STATES', '+18558229464', 'https://www.firstbank.com'),
    ('480967', 'VISA', 'DEBIT', 'CHECK CARD', 'CHARLES SCHWAB BANK', 'United States', '1-888-403-9000', 'www.schwabbank.com/'),
    ('480968', 'VISA', 'DEBIT', 'CLASSIC', 'RIVERVIEW COMMUNITY BANK', 'United States', '800-822-2076', 'www.riverviewbank.com/'),
    ('480969', 'VISA', 'CREDIT', 'PREMIER', 'CREDIT UNION OF COLORADO', 'United States', '800-444-4816', 'www.cuofco.org'),
    ('480970', 'VISA', 'CREDIT', 'BUSINESS', 'ARIZONA CENTRAL C.U.', 'United States', '(866) 264-6421', 'www.azcentralcu.org/'),
    ('480971', 'VISA', 'DEBIT', 'BUSINESS', 'ARIZONA CENTRAL C.U.', 'United States', '(866) 264-6421', 'www.azcentralcu.org/'),
    ('480972', 'VISA', 'DEBIT', 'CLASSIC', 'FIRST TRI COUNTY BANK', 'United States', '402.656.3885', 'https://ftcb1.com/'),
    ('480973', 'VISA', 'DEBIT', 'CLASSIC', 'PACIFIC NORTHWEST IRONWORKERS F.C.U.', 'United States', '1-877-769-4766', 'https://ironworkersfcu.org/'),
    ('480974', 'VISA', 'CREDIT', 'TRADITIONAL', 'FINANCIAL PARTNERS CREDIT UNION', 'UNITED STATES', '+18009507328', 'https://fpcu.org'),
    ('480975', 'VISA', 'CREDIT', 'CLASSIC', 'PLAINS COMMERCE BANK', 'United States', '877.227.7548', 'www.plainscommerce.com'),
    ('480976', 'VISA', 'DEBIT', 'CLASSIC', 'BANK OF THE SIERRA', 'United States', '1-888-454-BANK', 'https://www.bankofthesierra.com/'),
    ('480977', 'VISA', 'DEBIT', 'CLASSIC', 'QUEST FEDERAL CREDIT UNION', 'UNITED STATES', '+14196744998', 'https://questfcu.com'),
    ('480978', 'VISA', 'CREDIT', NULL, 'REGIONS BANK', 'United States', '1-800-734-4667', 'www.regions.com/personal-banking'),
    ('480979', 'VISA', 'DEBIT', 'CLASSIC', 'PEOPLES BANK AND TRUST COMPANY', 'United States', '(662) 237-9272', 'www.pbtconlane.com'),
    ('480980', 'VISA', 'DEBIT', 'ELECTRON', 'BANQUE INVIK, S.A.', 'Luxembourg', NULL, NULL),
    ('480981', 'VISA', 'DEBIT', 'ELECTRON', 'BANQUE INVIK, S.A.', 'Luxembourg', NULL, NULL),
    ('480982', 'VISA', 'DEBIT', 'ELECTRON', 'MERCANTILE DISCOUNT BANK, LTD.', 'Israel', '*3477', 'www.mercantile.co.il/MB/private/'),
    ('480983', 'VISA', 'DEBIT', 'ELECTRON', 'MERCANTILE DISCOUNT BANK, LTD.', 'Israel', '*3477', 'www.mercantile.co.il/MB/private/'),
    ('480984', 'VISA', 'DEBIT', 'ELECTRON', 'MERCANTILE DISCOUNT BANK, LTD.', 'Israel', '*3477', 'www.mercantile.co.il/MB/private/'),
    ('480985', 'VISA', 'CREDIT', 'CLASSIC', 'DENVER COMMUNITY CREDIT UNION', 'UNITED STATES', '+13035731170', 'https://denvercommunity.coop'),
    ('480986', 'VISA', 'DEBIT', 'CLASSIC', 'WYO CENTRAL F.C.U.', 'United States', '307-234-5401', 'www.wyocentral.org/'),
    ('480987', 'VISA', 'DEBIT', 'CHECK CARD', 'CHARLES SCHWAB BANK', 'United States', '1-888-403-9000', 'www.schwabbank.com/'),
    ('480988', 'VISA', 'DEBIT', 'CLASSIC', 'ICBA BANCARD', 'United States', '800-242-4770', 'www.icba.org/bancard/homepage'),
    ('480989', 'VISA', 'DEBIT', 'CHECK CARD', 'CHARLES SCHWAB BANK', 'United States', '1-888-403-9000', 'www.schwabbank.com/'),
    ('480990', 'VISA', 'DEBIT', 'PLATINUM', 'CHARLES SCHWAB BANK', 'United States', '1-888-403-9000', 'www.schwabbank.com/'),
    ('480991', 'VISA', 'CREDIT', 'PLATINUM', 'INVEST BANK PLC', 'JORDAN', '58 (212) 92 98 31', 'http://www.investbank.jo'),
    ('480992', 'VISA', 'CREDIT', 'CLASSIC', 'CITITARJETAS DE HONDURAS, S.A.', 'Honduras', NULL, NULL),
    ('480993', 'VISA', 'CREDIT', 'CLASSIC', 'AVAL CARD, S.A. DE C.V.', 'Honduras', NULL, NULL),
    ('480994', 'VISA', 'CREDIT', 'GOLD', 'CITITARJETAS DE HONDURAS, S.A.', 'HONDURAS', '+50422160101', NULL),
    ('480995', 'VISA', 'CREDIT', 'GOLD PREMIUM', 'AVAL CARD, S.A. DE C.V.', 'Honduras', NULL, NULL),
    ('480996', 'VISA', 'CREDIT', NULL, 'RIAS S.R.L. (BANCOMAT)', 'Uruguay', NULL, NULL),
    ('480997', 'VISA', 'DEBIT', 'BUSINESS', 'CONNEX CREDIT UNION, INC.', 'UNITED STATES', '+12036035700', 'https://connexcu.org'),
    ('480998', 'VISA', 'DEBIT', 'ELECTRON', 'ESBANK ESKISEHIR BANKASI T.A.S.', 'Turkey', NULL, 'esbankemekder.com/'),
    ('480999', 'VISA', 'DEBIT', NULL, 'ROGUE F.C.U.', 'United States', '800.856.7328', 'www.roguecu.org/'),
    ('481000', 'VISA', 'DEBIT', 'PREPAID CLASSIC', 'MOONEY S.P.A.', 'ITALY', NULL, NULL),
    ('481001', 'VISA', 'CREDIT', 'GOLD', 'BOURSORAMA BANQUE', 'FRANCE', '+33800092009', 'https://www.boursorama-banque.com'),
    ('481002', 'VISA', 'DEBIT', 'BUSINESS', 'UNICREDIT BANK GMBH', 'GERMANY', NULL, NULL),
    ('481003', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481004', 'VISA', 'CREDIT', 'CORPORATE T&E', 'PAYRNET, LTD.', 'UNITED KINGDOM', NULL, NULL),
    ('481005', 'VISA', 'CREDIT', 'CORPORATE T&E', 'PAYNETICS AD', 'SWEDEN', NULL, NULL),
    ('481006', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481007', 'VISA', 'CREDIT', 'CLASSIC', 'ABANCA CORPORACION BANCARIA, S.A', 'PORTUGAL', NULL, NULL),
    ('481008', 'VISA', 'DEBIT', 'PREPAID', 'IMAGOR, S.A.', 'BELGIUM', NULL, NULL),
    ('481009', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481010', 'VISA', 'CREDIT', 'BUSINESS', 'CBNK BANCO DE COLECTIVOS, S.A.', 'SPAIN', NULL, NULL),
    ('481011', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481012', 'VISA', 'DEBIT', 'BUSINESS', 'CBNK BANCO DE COLECTIVOS, S.A.', 'SPAIN', NULL, NULL),
    ('481013', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481014', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481015', 'VISA', 'DEBIT', 'PREPAID BUSINESS', 'PAYMENTSENSE, LTD.', 'UNITED KINGDOM', NULL, NULL),
    ('481016', 'VISA', 'DEBIT', 'BUSINESS', 'PAYRNET, LTD.', 'UNITED KINGDOM', NULL, NULL),
    ('481017', 'VISA', 'DEBIT', 'BUSINESS', 'UAB PAYRNET', 'SWEDEN', NULL, NULL),
    ('481018', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481019', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481020', 'VISA', 'DEBIT', 'CLASSIC', 'LANDESBANK HESSEN-THUERINGEN GIROZENTRALE', 'GERMANY', NULL, NULL),
    ('481021', 'VISA', 'DEBIT', 'PREPAID CLASSIC', 'BPCE', 'FRANCE', NULL, NULL),
    ('481022', 'VISA', 'DEBIT', 'BUSINESS', 'PAYMENTSENSE, LTD.', 'UNITED KINGDOM', NULL, NULL),
    ('481023', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481024', 'VISA', 'CREDIT', 'CORPORATE T&E', 'BANCO COMERCIAL PORTUGUES, S.A.', 'PORTUGAL', NULL, NULL),
    ('481025', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481026', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481027', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481028', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481029', 'VISA', 'DEBIT', 'INFINITE', 'NEXI PAYMENTS S.P.A.', 'ITALY', '+18004736896', 'https://www.nexi.it'),
    ('481030', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481031', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481032', 'VISA', 'DEBIT', 'CLASSIC', 'UAB NUVEI', 'LITHUANIA', NULL, NULL),
    ('481033', 'VISA', 'DEBIT', 'PLATINUM', 'XAPO BANK, LTD.', 'PARAGUAY', NULL, NULL),
    ('481034', 'VISA', 'DEBIT', 'BUSINESS', 'XAPO BANK, LTD.', 'GIBRALTAR', NULL, NULL),
    ('481035', 'VISA', 'DEBIT', 'CLASSIC', 'MBANK, S.A.', 'SLOVAKIA', NULL, 'https://www.mbank.pl'),
    ('481036', 'VISA', 'DEBIT', 'CLASSIC', 'MBANK, S.A.', 'CZECH REPUBLIC', NULL, 'https://www.mbank.pl'),
    ('481037', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL);

INSERT OR REPLACE INTO bins (bin, brand, type, category, issuer, country, bank_phone, bank_url) VALUES
    ('481038', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481039', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481040', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481041', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481042', 'VISA', 'DEBIT', 'PREPAID PRIVATE LABEL STANDARD', NULL, 'UNITED KINGDOM', NULL, NULL),
    ('481043', 'VISA', 'DEBIT', 'PREPAID PRIVATE LABEL STANDARD', NULL, 'UNITED KINGDOM', NULL, NULL),
    ('481044', 'VISA', 'DEBIT', 'CLASSIC', 'INTERGIRO INTL AB (PUBL)', 'SWEDEN', NULL, NULL),
    ('481045', 'VISA', 'CREDIT', 'CLASSIC', 'TRANSACT PAYMENTS, LTD.', 'UNITED KINGDOM', NULL, NULL),
    ('481046', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481047', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481048', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481049', 'VISA', 'DEBIT', 'BUSINESS', 'DIVILO FINTECH, SL', 'SPAIN', NULL, NULL),
    ('481050', 'VISA', 'CREDIT', 'CORPORATE T&E', 'DIVILO FINTECH, SL', 'SPAIN', NULL, NULL),
    ('481051', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481052', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481053', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481054', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481055', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481056', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481057', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481058', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481059', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481060', 'VISA', 'CREDIT', 'PLATINUM', 'BARCLAYS BANK UK PLC', 'UNITED KINGDOM', NULL, NULL),
    ('481061', 'VISA', 'DEBIT', 'PREPAID VPAY', 'RIGHTCARD PAYMENT SERVICES, LTD.', 'UNITED KINGDOM', NULL, NULL),
    ('481062', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481063', 'VISA', 'CREDIT', 'INFINITE BUSINESS', 'PLIANT OY', 'SPAIN', NULL, NULL),
    ('481064', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481065', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481066', 'VISA', 'DEBIT', 'CLASSIC', 'TOLGA-OS SPAREBANK', 'NORWAY', NULL, NULL),
    ('481067', 'VISA', 'DEBIT', 'CLASSIC', 'TOLGA-OS SPAREBANK', 'NORWAY', NULL, NULL),
    ('481068', 'VISA', 'DEBIT', 'BUSINESS', 'TOLGA-OS SPAREBANK', 'NORWAY', NULL, NULL),
    ('481069', 'VISA', 'DEBIT', 'PREPAID CLASSIC', 'SOLARIS SE', 'GERMANY', NULL, NULL),
    ('481070', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481071', 'VISA', 'DEBIT', 'BUSINESS', 'ADYEN, N.V.', 'UNITED KINGDOM', NULL, NULL),
    ('481072', 'VISA', 'DEBIT', 'BUSINESS', 'ADYEN, N.V.', 'SWEDEN', NULL, NULL),
    ('481073', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481074', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481075', 'VISA', 'DEBIT', 'PREPAID CLASSIC', 'KLARNA BANK AB', 'UNITED KINGDOM', NULL, NULL),
    ('481076', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481077', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481078', 'VISA', 'DEBIT', 'PLATINUM', 'CBH - COMPAGNIE BANCAIRE HELVETIQUE, S.A.', 'SWITZERLAND', NULL, 'http://www.cbhbank.com'),
    ('481079', 'VISA', 'DEBIT', 'CLASSIC', 'NEWB', 'LUXEMBOURG', NULL, NULL),
    ('481080', 'VISA', 'CREDIT', 'BUSINESS', 'ZEVOY AKTIEBOLAG', 'POLAND', NULL, NULL),
    ('481081', 'VISA', 'DEBIT', 'CLASSIC', 'COSMOTE PAYMENTS ELECTRONIC MONEY SERVICES, S.A.', 'GREECE', NULL, NULL),
    ('481082', 'VISA', 'DEBIT', 'BUSINESS', 'COSMOTE PAYMENTS ELECTRONIC MONEY SERVICES, S.A.', 'GREECE', NULL, NULL),
    ('481083', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481084', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481085', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('481086', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481087', 'VISA', 'DEBIT', 'CLASSIC', 'PLANET PAY SPOLKA Z OGRANICZONA ODPOWIEDZIALNOSCIA', 'POLAND', NULL, NULL),
    ('481088', 'VISA', 'CREDIT', 'CLASSIC', 'PLANET PAY SPOLKA Z OGRANICZONA ODPOWIEDZIALNOSCIA', 'POLAND', NULL, NULL),
    ('481089', 'VISA', 'DEBIT', 'PREPAID CLASSIC', 'PLANET PAY SPOLKA Z OGRANICZONA ODPOWIEDZIALNOSCIA', 'POLAND', NULL, NULL),
    ('481090', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481091', 'VISA', 'CREDIT', 'BUSINESS', 'BPCE', 'FRANCE', NULL, NULL),
    ('481092', 'VISA', 'DEBIT', 'PLATINUM', 'BPCE', 'FRANCE', NULL, NULL),
    ('481093', 'VISA', 'DEBIT', 'PREPAID CLASSIC', 'TREEZOR SAS', 'FRANCE', '+33184192981', 'https://www.treezor.com'),
    ('481094', 'VISA', 'CREDIT', NULL, NULL, 'SWEDEN', NULL, NULL),
    ('481095', 'VISA', 'DEBIT', 'INFINITE', 'BPCE', 'FRANCE', NULL, NULL),
    ('481096', 'VISA', 'CREDIT', NULL, NULL, 'SWEDEN', NULL, NULL),
    ('481097', 'VISA', 'DEBIT', 'GOLD', 'EUROBANK, S.A.', 'GREECE', NULL, NULL),
    ('481098', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481099', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481100', 'VISA', 'CREDIT', 'CLASSIC', 'BANK OF HAWAII', 'United States', '643-3888', 'www.boh.com/personal/'),
    ('481101', 'VISA', 'CREDIT', 'TRADITIONAL', 'HAR-CO CREDIT UNION', 'UNITED STATES', NULL, NULL),
    ('481102', 'VISA', 'DEBIT', 'CLASSIC', 'BANK OF HAWAII', 'United States', '643-3888', 'www.boh.com/personal/'),
    ('481103', 'VISA', 'CREDIT', NULL, 'BANK OF HAWAII', 'UNITED STATES', '+18886433888', 'https://www.boh.com'),
    ('481104', 'VISA', 'DEBIT', 'PREPAID CLASSIC', 'FRANKLIN TRUST FEDERAL CREDIT UNION', 'UNITED STATES', '+18602964379', 'https://franklintrust.org'),
    ('481105', 'VISA', 'DEBIT', 'CLASSIC', 'WORCESTER POLICE DEPARTMENT CREDIT UNION', 'UNITED STATES', NULL, NULL),
    ('481106', 'VISA', 'DEBIT', 'CLASSIC', 'WUFFACE FEDERAL CREDIT UNION', 'UNITED STATES', NULL, NULL),
    ('481107', 'VISA', 'CREDIT', 'TRADITIONAL', 'VOLT CREDIT UNION', 'UNITED STATES', NULL, NULL),
    ('481108', 'VISA', 'DEBIT', 'CLASSIC', 'SUMMIT HAMPTON ROADS FEDERAL CREDIT UNION', 'UNITED STATES', NULL, NULL),
    ('481109', 'VISA', 'DEBIT', 'CLASSIC', 'BANK OF HAWAII', 'United States', '643-3888', 'www.boh.com/personal/'),
    ('481110', 'VISA', 'DEBIT', 'CLASSIC', 'BANK OF HAWAII', 'United States', '643-3888', 'www.boh.com/personal/'),
    ('481111', 'VISA', 'CREDIT', 'PLATINUM', 'INVEST BANK PLC', 'JORDAN', '58 (212) 92 98 31', 'http://www.investbank.jo'),
    ('481112', 'VISA', 'DEBIT', 'BUSINESS', 'BANK OF HAWAII', 'United States', '643-3888', 'www.boh.com/personal/'),
    ('481113', 'VISA', 'CREDIT', 'BUSINESS', 'NORTHWEST BANK', 'UNITED STATES', '+18776725678', 'https://www.northwest.bank'),
    ('481114', 'VISA', 'CREDIT', 'SIGNATURE', 'WRIGHT PATMAN CONGRESSIONAL FEDERAL CREDIT UNION', 'UNITED STATES', '+17039348300', 'https://www.congressionalfcu.org'),
    ('481115', 'VISA', 'DEBIT', 'CLASSIC', 'RAH FEDERAL CREDIT UNION', 'UNITED STATES', NULL, NULL),
    ('481116', 'VISA', 'DEBIT', 'CLASSIC', 'GUARANTY BANK AND TRUST COMPANY', 'UNITED STATES', NULL, NULL),
    ('481117', 'VISA', 'DEBIT', 'PREPAID CLASSIC', 'TWO HARBORS FEDERAL CREDIT UNION', 'UNITED STATES', '+12188342266', 'https://www.thfcu.org'),
    ('481118', 'VISA', 'DEBIT', 'PREPAID CLASSIC', 'VISION ONE CREDIT UNION', 'UNITED STATES', NULL, NULL),
    ('481119', 'VISA', 'DEBIT', 'CLASSIC', 'STATE BANK OF SCOTIA', 'UNITED STATES', NULL, NULL),
    ('481120', 'VISA', 'DEBIT', 'CLASSIC', 'FIRST CAPITAL FEDERAL CREDIT UNION', 'UNITED STATES', '+18008932328', 'https://www.firstcapitalfcu.com'),
    ('481121', 'VISA', 'CREDIT', NULL, 'BANK OF HAWAII', 'UNITED STATES', '+18886433888', 'https://www.boh.com'),
    ('481122', 'VISA', 'CREDIT', NULL, 'BANK OF HAWAII', 'UNITED STATES', '+18886433888', 'https://www.boh.com'),
    ('481123', 'VISA', 'CREDIT', 'PRIVATE LABEL BASIC', 'BANK OF HAWAII', 'UNITED STATES', '+18886433888', 'https://www.boh.com'),
    ('481124', 'VISA', 'CREDIT', 'CLASSIC', 'THE BANK OF NOVA SCOTIA', 'CANADA', NULL, NULL),
    ('481125', 'VISA', 'CREDIT', 'CLASSIC', 'THE BANK OF NOVA SCOTIA', 'CANADA', NULL, NULL),
    ('481126', 'VISA', 'CREDIT', 'CLASSIC', 'THE BANK OF NOVA SCOTIA', 'CANADA', NULL, NULL),
    ('481127', 'VISA', 'CREDIT', 'CLASSIC', 'THE BANK OF NOVA SCOTIA', 'CANADA', NULL, NULL),
    ('481128', 'VISA', 'CREDIT', 'CLASSIC', 'THE BANK OF NOVA SCOTIA', 'CANADA', NULL, NULL),
    ('481129', 'VISA', 'CREDIT', 'GOLD', 'THE BANK OF NOVA SCOTIA', 'CANADA', NULL, NULL),
    ('481130', 'VISA', 'CREDIT', 'BUSINESS', 'THE BANK OF NOVA SCOTIA', 'CANADA', NULL, NULL),
    ('481131', 'VISA', 'CREDIT', 'BUSINESS', 'THE BANK OF NOVA SCOTIA', 'CANADA', NULL, NULL),
    ('481132', 'VISA', 'CREDIT', 'INFINITE', 'STANDARD CHARTERED BANK', 'SINGAPORE', '+6518007477000', 'https://www.sc.com'),
    ('481133', 'VISA', 'CREDIT', 'SIGNATURE', 'VISECA PAYMENT SERVICES SA', 'SWITZERLAND', NULL, NULL),
    ('481134', 'VISA', 'DEBIT', 'CLASSIC', 'BANCO POPULAR DE PUERTO RICO', 'PUERTO RICO', '+17877659800', 'http://www.popular.com'),
    ('481135', 'VISA', 'DEBIT', 'CLASSIC', 'FIRST BANK', 'United States', '940.691.0000', 'www.firstbankweb.com'),
    ('481136', 'VISA', 'DEBIT', 'CLASSIC', 'SERVICES C.U.', 'United States', NULL, NULL),
    ('481137', 'VISA', 'CREDIT', 'PLATINUM', 'INVEST BANK PLC', 'JORDAN', '58 (212) 92 98 31', 'http://www.investbank.jo');

INSERT OR REPLACE INTO bins (bin, brand, type, category, issuer, country, bank_phone, bank_url) VALUES
    ('481138', 'VISA', 'CREDIT', 'PLATINUM', 'SOUTHERN F.C.U.', 'United States', '713-232-7774', 'www.southernfederalcu.org'),
    ('481139', 'VISA', 'DEBIT', 'CLASSIC', '1ST UNITED SERVICES C.U.', 'United States', '(800) 649-0193', 'www.1stunitedcu.org'),
    ('481140', 'VISA', 'CREDIT', 'BUSINESS', 'BANK OF HAWAII', 'United States', '643-3888', 'www.boh.com/personal/'),
    ('481141', 'VISA', 'CREDIT', 'CLASSIC', 'BANK OF HAWAII', 'United States', '643-3888', 'www.boh.com/personal/'),
    ('481142', 'VISA', 'CREDIT', 'BUSINESS', 'BANK OF HAWAII', 'United States', '643-3888', 'www.boh.com/personal/'),
    ('481143', 'VISA', 'CREDIT', 'CLASSIC', 'U.S. BANK, N.A.', 'United States', NULL, NULL),
    ('481144', 'VISA', 'CREDIT', 'CLASSIC', 'U.S. BANK, N.A.', 'United States', NULL, NULL),
    ('481145', 'VISA', 'CREDIT', 'CLASSIC', 'ROYAL BANK OF CANADA', 'CANADA', '44 1481 744126/744009', 'http://www.rbc.com'),
    ('481146', 'VISA', 'CREDIT', 'PLATINUM', 'ALLIANCE COMMUNITY F.C.U.', 'United States', NULL, NULL),
    ('481147', 'VISA', 'DEBIT', 'CLASSIC', 'ALLIANCE COMMUNITY F.C.U.', 'United States', NULL, NULL),
    ('481148', 'VISA', 'CREDIT', 'CLASSIC', 'ROYAL BANK OF CANADA', 'CANADA', '44 1481 744126/744009', 'http://www.rbc.com'),
    ('481149', 'VISA', 'DEBIT', 'CLASSIC', 'FIRST A NATIONAL BANKING ASSOCIATION', 'United States', '1-855-257-2265', 'www.thefirstbank.com'),
    ('481150', 'VISA', 'CREDIT', 'CLASSIC', 'ROYAL BANK OF CANADA', 'CANADA', '44 1481 744126/744009', 'http://www.rbc.com'),
    ('481151', 'VISA', 'CREDIT', 'CLASSIC', 'ROYAL BANK OF CANADA', 'CANADA', '44 1481 744126/744009', 'http://www.rbc.com'),
    ('481152', 'VISA', 'CREDIT', 'GOLD', 'ROYAL BANK OF CANADA', 'CANADA', '44 1481 744126/744009', 'http://www.rbc.com'),
    ('481153', 'VISA', 'CREDIT', 'PLATINUM', 'ROYAL BANK OF CANADA', 'CANADA', '44 1481 744126/744009', 'http://www.rbc.com'),
    ('481154', 'VISA', 'DEBIT', 'PLATINUM', 'OVERSEA-CHINESE BANKING CORPORATION, LTD.', 'SINGAPORE', NULL, NULL),
    ('481155', 'VISA', 'DEBIT', 'PLATINUM', 'OVERSEA-CHINESE BANKING CORPORATION, LTD.', 'SINGAPORE', NULL, NULL),
    ('481156', 'VISA', 'CREDIT', 'CLASSIC', 'BANCO POPULAR DE PUERTO RICO', 'PUERTO RICO', '+17877659800', 'http://www.popular.com'),
    ('481157', 'VISA', 'CREDIT', 'PLATINUM', 'BANCO POPULAR DE PUERTO RICO', 'PUERTO RICO', '+17877659800', 'http://www.popular.com'),
    ('481158', 'VISA', 'CREDIT', 'PLATINUM', 'BANCO POPULAR DE PUERTO RICO', 'PUERTO RICO', '+17877659800', 'http://www.popular.com'),
    ('481159', 'VISA', 'CREDIT', 'CLASSIC', 'BANCO POPULAR DE PUERTO RICO', 'PUERTO RICO', '+17877659800', 'http://www.popular.com'),
    ('481160', 'VISA', 'CREDIT', 'CLASSIC', 'BANCO POPULAR DE PUERTO RICO', 'PUERTO RICO', '+17877659800', 'http://www.popular.com'),
    ('481161', 'VISA', 'CREDIT', 'PLATINUM', 'BANCO POPULAR DE PUERTO RICO', 'PUERTO RICO', '+17877659800', 'http://www.popular.com'),
    ('481162', 'VISA', 'DEBIT', 'CLASSIC', 'SERVICES C.U.', 'United States', NULL, NULL),
    ('481163', 'VISA', 'CREDIT', 'CLASSIC', 'ATLANTIC SOUTH BANK', 'UNITED STATES', '+14782726262', 'https://www.atlanticsouthbank.com'),
    ('481164', 'VISA', 'CREDIT', 'PREMIER', 'WHEELER COUNTY STATE BANK', 'United States', NULL, 'www.atlanticsouthbank.com'),
    ('481165', 'VISA', 'DEBIT', 'BUSINESS', 'BANK OF HAWAII', 'United States', '643-3888', 'www.boh.com/personal/'),
    ('481166', 'VISA', 'DEBIT', 'CLASSIC', 'SOUTH GEORGIA BANK', 'UNITED STATES', '+19126541051', 'https://southgabank.com'),
    ('481167', 'VISA', 'DEBIT', 'CLASSIC', 'FIRST BANK', 'United States', '940.691.0000', 'www.firstbankweb.com'),
    ('481168', 'VISA', 'DEBIT', 'CLASSIC', 'BANK OF HAWAII', 'United States', '643-3888', 'www.boh.com/personal/'),
    ('481169', 'VISA', 'DEBIT', 'PREMIER', 'BANK OF HAWAII', 'United States', '643-3888', 'www.boh.com/personal/'),
    ('481170', 'VISA', 'DEBIT', 'PREPAID', 'BANK OF HAWAII', 'UNITED STATES', '+18886433888', 'https://www.boh.com'),
    ('481171', 'VISA', 'DEBIT', 'CLASSIC', 'SIMPLE CARD ISSUED BY BANCORP BANK', 'UNITED STATES', '+18882480632', 'https://www.simple.com'),
    ('481172', 'VISA', 'DEBIT', 'CLASSIC', 'GLASS CITY F.C.U.', 'United States', '419.887.1000', 'https://glasscityfcu.com/'),
    ('481173', 'VISA', NULL, NULL, 'BANK OF HAWAII', 'United States', '643-3888', 'www.boh.com/personal/'),
    ('481174', 'VISA', 'CREDIT', 'BUSINESS', 'CELTIC BANK', 'UNITED STATES', NULL, NULL),
    ('481175', 'VISA', 'CREDIT', 'BUSINESS', 'THE OHIO VALLEY BANK COMPANY', 'UNITED STATES', NULL, NULL),
    ('481176', 'VISA', 'CREDIT', 'TRADITIONAL', 'FIRST BANK & TRUST', 'UNITED STATES', '+18008431552', 'https://www.bankeasy.com'),
    ('481177', 'VISA', 'DEBIT', 'BUSINESS', 'THE FIRST NATIONAL BANK OF SCOTT CITY', 'UNITED STATES', '+16208722143', 'http://www.fnbscott.com'),
    ('481178', 'VISA', 'DEBIT', 'PREPAID', 'FIRST CENTURY BANK, N.A.', 'UNITED STATES', '+18003328231', 'https://myfirstcenturybank.com'),
    ('481179', 'VISA', 'DEBIT', 'CLASSIC', 'EVANSVILLE TEACHERS FEDERAL CREDIT UNION', 'UNITED STATES', '+18124779271', 'https://etfcu.org'),
    ('481180', 'VISA', 'DEBIT', 'PREPAID', 'COMMUNITY FEDERAL SAVINGS BANK', 'UNITED STATES', '+12128979650', 'https://www.cfsb.com'),
    ('481181', 'VISA', 'CREDIT', 'BUSINESS', 'ANDIGO CREDIT UNION', 'UNITED STATES', '+18475765199', 'https://www.andigo.org'),
    ('481182', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481183', 'VISA', 'CREDIT', 'BUSINESS', 'HERITAGE BANK', 'UNITED STATES', '+18004556126', 'https://www.heritagebanknw.com'),
    ('481184', 'VISA', 'CREDIT', 'CLASSIC', 'HERITAGE BANK', 'UNITED STATES', '+18004556126', 'https://www.heritagebanknw.com'),
    ('481185', 'VISA', 'DEBIT', 'PREPAID', 'GLACIER BANK', 'UNITED STATES', '+18007354371', 'https://www.glacierbank.com'),
    ('481186', 'VISA', 'DEBIT', 'PREPAID', 'UNITED BUSINESS BANK', 'UNITED STATES', '+19707260414', 'https://www.unitedbusinessbank.com'),
    ('481187', 'VISA', 'DEBIT', 'CLASSIC', 'WELLS FARGO BANK, N.A.', 'United States', NULL, NULL),
    ('481188', 'VISA', 'DEBIT', 'CLASSIC', 'MARION NATIONAL BANK', 'United States', '620-382-2109', 'www.bankwithmnb.com/home/home'),
    ('481189', 'VISA', 'DEBIT', 'CLASSIC', 'ARCHER CREDIT UNION', 'UNITED STATES', '+13087952204', 'https://archerccu.com'),
    ('481190', 'VISA', 'CREDIT', 'CLASSIC', 'BANK OF HAWAII', 'United States', '643-3888', 'www.boh.com/personal/'),
    ('481191', 'VISA', 'DEBIT', 'CLASSIC', 'ST FRANCIS FEDERAL CREDIT UNION', 'UNITED STATES', '+18642551660', 'http://www.stfrancisfcu.org'),
    ('481192', 'VISA', 'DEBIT', 'CLASSIC', 'FIRST CHOICE CREDIT UNION', 'UNITED STATES', '+15616410100', 'https://www.firstchoicecu.org'),
    ('481193', 'VISA', 'DEBIT', 'CLASSIC', 'BIDVEST BANK, LTD.', 'SOUTH AFRICA', NULL, 'http://www.bidvestbank.co.za'),
    ('481194', 'VISA', 'DEBIT', 'CLASSIC', 'FIRST NATIONAL BANK OF ORDWAY', 'UNITED STATES', '+17192673531', 'https://www.fnblasanimas.com'),
    ('481195', 'VISA', 'DEBIT', 'CLASSIC', 'CHINATRUST BANK (U.S.A.)', 'United States', NULL, NULL),
    ('481196', 'VISA', 'CREDIT', 'CLASSIC', 'BANK OF HAWAII', 'United States', '643-3888', 'www.boh.com/personal/'),
    ('481197', 'VISA', 'CREDIT', 'CLASSIC', 'BANK OF HAWAII', 'United States', '643-3888', 'www.boh.com/personal/'),
    ('481198', 'VISA', 'CREDIT', 'CLASSIC', 'BANK OF HAWAII', 'United States', '643-3888', 'www.boh.com/personal/'),
    ('481199', 'VISA', 'CREDIT', NULL, 'BANK OF HAWAII', 'UNITED STATES', '+18886433888', 'https://www.boh.com'),
    ('481200', 'VISA', 'CREDIT', 'CLASSIC', 'THE HOME STATE BANK', 'UNITED STATES', '+18154592000', 'https://www.homestbk.com'),
    ('481201', 'VISA', 'DEBIT', 'PREPAID CLASSIC', 'BANQUE INTERNATIONALE DE CAMEROUN POUR L''EPARGNE ET LE CREDIT', 'CAMEROON', NULL, NULL),
    ('481202', 'VISA', 'CREDIT', 'PLATINUM', 'GENBANK CB (LTD)', 'RUSSIAN FEDERATION', NULL, NULL),
    ('481203', 'VISA', 'CREDIT', NULL, NULL, 'SPAIN', NULL, NULL),
    ('481204', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481205', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481206', 'VISA', 'CREDIT', 'PLATINUM', 'AL BILAD BANK', 'SAUDI ARABIA', '9662918884', 'http://www.bankalbilad.com'),
    ('481207', 'VISA', 'CREDIT', 'CLASSIC', 'AL BILAD BANK', 'SAUDI ARABIA', '9662918884', 'http://www.bankalbilad.com'),
    ('481208', 'VISA', 'DEBIT', 'PLATINUM', 'ECOBANK COTE D''IVOIRE', 'COTE D''IVOIRE', '(225) 20 31 92 00', 'http://www.ecobank.com'),
    ('481209', 'VISA', 'DEBIT', 'CLASSIC/PLATINUM', 'ECOBANK SENEGAL', 'SENEGAL', NULL, NULL),
    ('481210', 'VISA', 'CREDIT', 'PLATINUM', 'ECOBANK GHANA, LTD.', 'SENEGAL', NULL, 'http://www.ecobank.com'),
    ('481211', 'VISA', 'DEBIT', 'PLATINUM', 'ECOBANK SENEGAL', 'SENEGAL', NULL, NULL),
    ('481212', 'VISA', 'DEBIT', 'CLASSIC', 'BANCO COMERCIAL E DE INVESTIMENTOS SARL', 'MOZAMBIQUE', '+25821353700', 'http://www.bci.co.mz'),
    ('481213', 'VISA', 'DEBIT', 'CLASSIC', 'COOPERATIVA DE POUPANCA E CREDITO, S.C.R.L', 'MOZAMBIQUE', NULL, NULL),
    ('481214', 'VISA', 'CREDIT', 'CLASSIC', 'MAUBANK, LTD.', 'MAURITIUS', NULL, NULL),
    ('481215', 'VISA', 'CREDIT', 'GOLD', 'MAUBANK, LTD.', 'MAURITIUS', NULL, NULL),
    ('481216', 'VISA', 'CREDIT', 'PLATINUM', 'MAUBANK, LTD.', 'MAURITIUS', NULL, NULL),
    ('481217', 'VISA', 'CREDIT', 'PLATINUM', 'MAUBANK, LTD.', 'MAURITIUS', NULL, NULL),
    ('481218', 'VISA', 'CREDIT', 'PLATINUM', 'MAUBANK, LTD.', 'MAURITIUS', NULL, NULL),
    ('481219', 'VISA', 'DEBIT', 'GOLD', 'ECOBANK GHANA, LTD.', 'CAMEROON', NULL, 'http://www.ecobank.com'),
    ('481220', 'VISA', 'CREDIT', 'PLATINUM', 'ECOBANK CAMEROUN, S.A.', 'CAMEROON', NULL, NULL),
    ('481221', 'VISA', 'CREDIT', NULL, 'THE PEOPLES BANK CO', 'UNITED STATES', '+14196782385', 'https://www.pbcbank.com'),
    ('481222', 'VISA', 'CREDIT', NULL, 'CYBERSOURCE', 'UNITED STATES', '+18007097779', 'https://www.cybersource.com'),
    ('481223', 'VISA', 'DEBIT', 'BUSINESS', 'REGIONS BANK', 'UNITED STATES', '+18007344667', 'https://www.regions.com'),
    ('481224', 'VISA', 'DEBIT', 'CLASSIC', 'REGIONS BANK', 'UNITED STATES', '+18007344667', 'https://www.regions.com'),
    ('481225', 'VISA', 'DEBIT', 'CLASSIC', 'REGIONS BANK', 'UNITED STATES', '+18007344667', 'https://www.regions.com'),
    ('481226', 'VISA', 'DEBIT', 'CLASSIC', 'REGIONS BANK', 'UNITED STATES', '+18007344667', 'https://www.regions.com'),
    ('481227', 'VISA', 'DEBIT', 'CLASSIC', 'REGIONS BANK', 'UNITED STATES', '+18007344667', 'https://www.regions.com'),
    ('481228', 'VISA', 'DEBIT', 'CLASSIC', 'REGIONS BANK', 'UNITED STATES', '+18007344667', 'https://www.regions.com'),
    ('481229', 'VISA', 'DEBIT', 'CLASSIC', 'REGIONS BANK', 'UNITED STATES', '+18007344667', 'https://www.regions.com'),
    ('481230', 'VISA', 'DEBIT', 'CLASSIC', 'REGIONS BANK', 'UNITED STATES', '+18007344667', 'https://www.regions.com'),
    ('481231', 'VISA', 'DEBIT', 'PREPAID CLASSIC', 'REGIONS BANK', 'UNITED STATES', '+18007344667', 'https://www.regions.com'),
    ('481232', 'VISA', 'CREDIT', 'BUSINESS', 'REGIONS BANK', 'UNITED STATES', '+18007344667', 'https://www.regions.com'),
    ('481233', 'VISA', 'DEBIT', 'PREPAID CLASSIC', 'FIFTH THIRD BANK', 'UNITED STATES', '+15022312628', 'https://www.53.com'),
    ('481234', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481235', 'VISA', 'DEBIT', 'CLASSIC', 'FIRST BANK & TRUST CO.', 'UNITED STATES', '+18558229464', 'https://www.firstbank.com'),
    ('481236', 'VISA', 'DEBIT', 'BUSINESS', 'FIRST BANK & TRUST CO.', 'UNITED STATES', '+18558229464', 'https://www.firstbank.com'),
    ('481237', 'VISA', 'DEBIT', 'PREPAID', 'BANCORP BANK', 'UNITED STATES', '+18005450289', 'https://www.thebancorp.com');

INSERT OR REPLACE INTO bins (bin, brand, type, category, issuer, country, bank_phone, bank_url) VALUES
    ('481238', 'VISA', 'DEBIT', 'PREPAID PURCHASING', 'PEOPLES STATE BANK', 'UNITED STATES', '+18889299902', 'https://www.bankpeoples.com'),
    ('481239', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481240', 'VISA', 'CREDIT', 'TRADITIONAL', 'SOLIDARITY COMMUNITY FEDERAL CREDIT UNION', 'UNITED STATES', NULL, NULL),
    ('481241', 'VISA', 'CREDIT', 'TRADITIONAL', 'REGIONS BANK', 'UNITED STATES', '+18007344667', 'https://www.regions.com'),
    ('481242', 'VISA', 'CREDIT', 'TRADITIONAL', 'REGIONS BANK', 'UNITED STATES', '+18007344667', 'https://www.regions.com'),
    ('481243', 'VISA', 'CREDIT', 'TRADITIONAL', 'REGIONS BANK', 'UNITED STATES', '+18007344667', 'https://www.regions.com'),
    ('481244', 'VISA', 'DEBIT', 'BUSINESS', 'JPMORGAN CHASE BANK N.A. - DEBIT', 'UNITED STATES', NULL, NULL),
    ('481245', 'VISA', 'DEBIT', 'BUSINESS', 'REGIONS BANK', 'UNITED STATES', '+18007344667', 'https://www.regions.com'),
    ('481246', 'VISA', 'DEBIT', 'CLASSIC', 'REGIONS BANK', 'UNITED STATES', '+18007344667', 'https://www.regions.com'),
    ('481247', 'VISA', 'DEBIT', 'CLASSIC', 'REGIONS BANK', 'UNITED STATES', '+18007344667', 'https://www.regions.com'),
    ('481248', 'VISA', 'DEBIT', 'CLASSIC', 'REGIONS BANK', 'UNITED STATES', '+18007344667', 'https://www.regions.com'),
    ('481249', 'VISA', 'DEBIT', 'CLASSIC', 'REGIONS BANK', 'UNITED STATES', '+18007344667', 'https://www.regions.com'),
    ('481250', 'VISA', 'DEBIT', 'CLASSIC', 'REGIONS BANK', 'UNITED STATES', '+18007344667', 'https://www.regions.com'),
    ('481251', 'VISA', 'CREDIT', 'CLASSIC', 'UNION BANK OF MENA', 'United States', '479.394.2211', 'www.unionbankofmena.com/'),
    ('481252', 'VISA', 'CREDIT', 'CLASSIC', 'UMB BANK, N.A.', 'United States', NULL, NULL),
    ('481253', 'VISA', 'CREDIT', 'BUSINESS', 'AMERICA''S CREDIT UNION, A FEDERAL CREDIT UNION', 'UNITED STATES', '+19724945328', 'https://www.americascu.org'),
    ('481254', 'VISA', 'DEBIT', 'CLASSIC', 'CALIFORNIA CREDIT UNION', 'UNITED STATES', '+18003348788', 'https://www.ccu.com'),
    ('481255', 'VISA', 'DEBIT', 'CLASSIC', 'NORTHRIM BANK', 'UNITED STATES', '+18004782265', 'https://www.northrim.com'),
    ('481256', 'VISA', 'DEBIT', 'CLASSIC', 'TELHIO CREDIT UNION, INC.', 'United States', '614.221.3233', 'www.telhio.org'),
    ('481257', 'VISA', 'CREDIT', 'TRADITIONAL REWARDS', 'UNITED CREDIT UNION', 'UNITED STATES', '+18775818651', 'https://www.unitedcu.org'),
    ('481258', 'VISA', 'CREDIT', 'BUSINESS', 'THE FIDELITY BANK', 'UNITED STATES', NULL, NULL),
    ('481259', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481260', 'VISA', 'CREDIT', 'BUSINESS', 'ORANGE COUNTY''S CREDIT UNION', 'UNITED STATES', '+18883546228', 'https://www.orangecountyscu.org'),
    ('481261', 'VISA', 'DEBIT', 'BUSINESS', 'WESTPAC BANKING CORPORATION', 'PAPUA NEW GUINEA', '+6753220888', 'http://www.westpac.com.au'),
    ('481262', 'VISA', 'DEBIT', 'CLASSIC', 'TONGA DEVELOPMENT BANK, LTD.', 'TONGA', NULL, NULL),
    ('481263', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481264', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481265', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481266', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481267', 'VISA', 'CREDIT', 'BUSINESS', 'BSP FINANCIAL GROUP, LTD.', 'COOK ISLANDS', NULL, NULL),
    ('481268', 'VISA', 'CREDIT', 'BUSINESS', 'BSP FINANCIAL GROUP, LTD.', 'SOLOMON ISLANDS', NULL, NULL),
    ('481269', 'VISA', 'CREDIT', 'BUSINESS', 'BANK OF SOUTH PACIFIC TONGA, LTD.', 'TONGA', NULL, NULL),
    ('481270', 'VISA', 'CREDIT', 'BUSINESS', 'WESTPAC BANKING CORPORATION', 'PAPUA NEW GUINEA', '+6753220888', 'http://www.westpac.com.au'),
    ('481271', 'VISA', 'CREDIT', 'BUSINESS', 'BANK SOUTH PACIFIC (VANUATU), LTD.', 'VANUATU', NULL, NULL),
    ('481272', 'VISA', 'CREDIT', 'BUSINESS', 'BANK SOUTH PACIFIC (SAMOA), LTD.', 'SAMOA', NULL, NULL),
    ('481273', 'VISA', 'CREDIT', 'PURCHASING', 'BRADESCARD MEXICO, S. DE R.L.', 'MEXICO', NULL, NULL),
    ('481274', 'VISA', 'CREDIT', 'CLASSIC', 'BANCO SANTANDER, S.A.', 'BRAZIL', NULL, 'http://www.santander.com'),
    ('481275', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481276', 'VISA', 'CREDIT', 'GOLD', NULL, 'BRAZIL', NULL, NULL),
    ('481277', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481278', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481279', 'VISA', 'DEBIT', 'CLASSIC', 'BANCO NACIONAL DEL EJERCITO, FUERZA AEREA Y ARMADA, S.N.C.', 'MEXICO', '+525553282354', 'https://www.banjercito.com.mx'),
    ('481280', 'VISA', 'CREDIT', 'SIGNATURE', 'BANCO DE FINANZAS, S.A.', 'NICARAGUA', NULL, 'http://www.secure.bdfnet.com'),
    ('481281', 'VISA', 'CREDIT', 'CLASSIC', 'BRADESCARD MEXICO, S. DE R.L.', 'MEXICO', NULL, NULL),
    ('481282', 'VISA', 'CREDIT', 'CLASSIC', 'BRADESCARD MEXICO, S. DE R.L.', 'MEXICO', NULL, NULL),
    ('481283', 'VISA', 'CREDIT', 'CLASSIC', 'BRADESCARD MEXICO, S. DE R.L.', 'MEXICO', NULL, NULL),
    ('481284', 'VISA', 'CREDIT', 'CLASSIC', 'BRADESCARD MEXICO, S. DE R.L.', 'MEXICO', NULL, NULL),
    ('481285', 'VISA', 'DEBIT', 'PREPAID PLATINUM', 'CANADIAN IMPERIAL BANK OF COMMERCE', 'CANADA', '+18004654653', 'http://www.cibc.com'),
    ('481286', 'VISA', 'DEBIT', 'PREPAID PLATINUM', 'CANADIAN IMPERIAL BANK OF COMMERCE', 'CANADA', '+18004654653', 'http://www.cibc.com'),
    ('481287', 'VISA', 'DEBIT', 'PREPAID PLATINUM', 'CANADIAN IMPERIAL BANK OF COMMERCE', 'CANADA', '+18004654653', 'http://www.cibc.com'),
    ('481288', 'VISA', 'DEBIT', 'PREPAID PLATINUM', 'CANADIAN IMPERIAL BANK OF COMMERCE', 'CANADA', '+18004654653', 'http://www.cibc.com'),
    ('481289', 'VISA', 'CREDIT', 'GOLD', 'BANCO AGROMERCANTIL DE GUATEMALA, S.A.', 'GUATEMALA', NULL, NULL),
    ('481290', 'VISA', 'CREDIT', 'INFINITE', 'BANCO DEL CARIBE C.A., BANCO UNIVERSAL', 'VENEZUELA, BOLIVARIAN REPUBLIC OF', NULL, NULL),
    ('481291', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481292', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481293', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481294', 'VISA', 'DEBIT', 'CLASSIC', 'PORT OF HAMPTON ROADS ILA FEDERAL CREDIT UNION', 'UNITED STATES', NULL, NULL),
    ('481295', 'VISA', 'DEBIT', 'BUSINESS', 'NORTHERN CREDIT UNION', 'UNITED STATES', NULL, NULL),
    ('481296', 'VISA', 'DEBIT', NULL, NULL, 'MEXICO', NULL, NULL),
    ('481297', 'VISA', 'DEBIT', 'CLASSIC', 'CODE CREDIT UNION', 'UNITED STATES', '+19372228971', 'https://www.codecu.org'),
    ('481298', 'VISA', 'DEBIT', 'CLASSIC', 'FARMERS STATE BANK', 'UNITED STATES', '+18884927111', 'https://www.farmersstatebank.com'),
    ('481299', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481300', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481301', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481302', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481303', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481304', 'VISA', 'DEBIT', NULL, NULL, 'ARMENIA', NULL, NULL),
    ('481305', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481306', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481307', 'VISA', 'CREDIT', 'CLASSIC', 'BANK OF AMERICA, NATIONAL ASSOCIATION', 'UNITED STATES', '+18004321000', 'https://www.bankofamerica.com'),
    ('481308', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481309', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481310', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481311', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481312', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481313', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481314', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481315', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481316', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481317', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481318', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481319', 'VISA', 'DEBIT', NULL, NULL, 'VIET NAM', NULL, NULL),
    ('481320', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481321', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481322', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481323', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481324', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481325', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481326', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481327', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481328', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481329', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481330', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481331', 'VISA', 'CREDIT', NULL, NULL, 'FRANCE', NULL, NULL),
    ('481332', 'VISA', 'CREDIT', NULL, NULL, 'FRANCE', NULL, NULL),
    ('481333', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481334', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481335', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481336', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('481337', 'VISA', 'CREDIT', NULL, NULL, 'UNITED STATES', NULL, NULL);

COMMIT;
