-- Batch 677 - 500 records
BEGIN TRANSACTION;

INSERT OR REPLACE INTO bins (bin, brand, type, category, issuer, country, bank_phone, bank_url) VALUES
    ('603338', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603339', 'MAESTRO', 'DEBIT', NULL, NULL, 'BRAZIL', NULL, NULL),
    ('603340', 'MAESTRO', 'DEBIT', NULL, 'REDECARD, S.A.', 'BRAZIL', NULL, 'http://www.redecard.com.br'),
    ('603341', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('603342', 'MAESTRO', 'DEBIT', 'GIFT', 'BANCO DO BRASIL, S.A.', 'BRAZIL', '+558007290722', 'http://www.bb.com.br'),
    ('603343', 'MAESTRO', 'DEBIT', NULL, 'ZIRAAT BANKASI', 'Turkey', NULL, NULL),
    ('603344', 'MAESTRO', 'DEBIT', NULL, 'VISA COLOMBIA', 'Colombia', '01-800-912-2066', 'www.visa.com.co'),
    ('603345', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603346', 'MAESTRO', 'DEBIT', NULL, NULL, 'MALAYSIA', NULL, NULL),
    ('603347', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603348', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603349', 'MAESTRO', 'DEBIT', 'PERSONAL', 'NATIONS TRUST BANK', 'UNITED STATES', NULL, NULL),
    ('603350', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603351', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('603352', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603353', 'MAESTRO', 'DEBIT', NULL, NULL, 'EGYPT', NULL, NULL),
    ('603354', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603355', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603356', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603357', 'EBT', 'DEBIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('603358', 'EBT', 'DEBIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('603359', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603360', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603361', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603362', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603363', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603364', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603365', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603366', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603367', 'CHINA UNION PAY', 'DEBIT', NULL, 'BANK OF HANGZHOU', 'CHINA', '95398', 'http://www.hzbank.com.cn'),
    ('603368', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603369', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603370', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603371', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603372', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603373', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603374', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603375', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603376', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603377', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603378', 'MAESTRO', 'DEBIT', NULL, NULL, 'BRAZIL', NULL, NULL),
    ('603379', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603380', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603381', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603382', 'MAESTRO', 'DEBIT', 'STANDARD', 'LA CAIXA', 'SPAIN', NULL, NULL),
    ('603383', 'MAESTRO', 'DEBIT', NULL, NULL, 'SPAIN', NULL, NULL),
    ('603384', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603385', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603386', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603387', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603388', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603389', 'SODEXO', 'DEBIT', NULL, 'SODEXO PASS DO BRASIL', 'BRAZIL', NULL, NULL),
    ('603390', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603391', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603392', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603393', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603394', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603395', 'MAESTRO', 'DEBIT', NULL, 'UNIBANCO - UNIAO DE BANCOS BRASILEIROS, S.A.', 'Panama', '297-6000', 'www.unibank.com.pa'),
    ('603396', 'MAESTRO', 'DEBIT', NULL, NULL, 'BRAZIL', NULL, NULL),
    ('603397', 'MAESTRO', 'DEBIT', NULL, 'SODEXO PASS DO BRASIL', 'BRAZIL', NULL, NULL),
    ('603398', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603399', 'MAESTRO', 'DEBIT', 'STANDARD', 'REDECARD, S.A.', 'BRAZIL', NULL, 'http://www.redecard.com.br'),
    ('603400', 'MAESTRO', 'DEBIT', 'PERSONAL', NULL, 'UNITED STATES', NULL, NULL),
    ('603401', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603402', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603403', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603404', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603405', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603406', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603407', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603408', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603409', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'BRAZIL', NULL, NULL),
    ('603410', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603411', 'EBT', 'DEBIT', 'GIFT', 'PACIFIC PREMIER BANK', 'UNITED STATES', '+18553434070', 'https://www.ppbi.com'),
    ('603412', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603413', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603414', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603415', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603416', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603417', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603418', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603419', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603420', 'MAESTRO', 'DEBIT', NULL, NULL, 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', NULL, NULL),
    ('603421', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603422', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603423', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603424', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603425', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603426', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603427', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603428', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603429', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603430', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603431', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603432', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603433', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603434', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603435', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603436', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603437', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL);

INSERT OR REPLACE INTO bins (bin, brand, type, category, issuer, country, bank_phone, bank_url) VALUES
    ('603438', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603439', 'PRIVATE LABEL', 'DEBIT', 'STANDARD', 'OCBC NISP BANK', 'INDONESIA', '+621500999', 'https://www.ocbcnisp.com'),
    ('603440', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603441', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603442', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603443', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603444', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603445', 'MAESTRO', 'DEBIT', NULL, 'GUANGZHOU CITY COMMERCIAL BANK', 'CHINA', '96699', 'http://www.gzcb.com.cn'),
    ('603446', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603447', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603448', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603449', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603450', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'UNITED STATES', NULL, NULL),
    ('603451', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603452', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603453', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603454', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603455', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603456', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603457', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603458', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603459', 'EBT', 'DEBIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('603460', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603461', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603462', 'PRIVATE LABEL', 'DEBIT', 'GIFT', NULL, 'UNITED STATES', NULL, NULL),
    ('603463', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603464', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603465', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603466', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603467', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603468', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603469', 'EBT', 'DEBIT', 'GIFT', 'DUNKIN DONUTS', 'UNITED STATES', '+18004470013', 'https://www.dunkindonuts.com'),
    ('603470', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603471', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603472', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603473', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603474', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603475', 'MAESTRO', 'DEBIT', NULL, NULL, 'BRAZIL', NULL, NULL),
    ('603476', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603477', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603478', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603479', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603480', 'MAESTRO', 'DEBIT', NULL, 'TURKIYE GARANTI BANKASI, A.S.', 'TURKEY', '+902123181818', 'http://www.garanti.com.tr'),
    ('603481', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603482', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603483', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603484', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603485', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603486', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603487', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603488', 'PRIVATE LABEL', 'DEBIT', NULL, NULL, 'ARGENTINA', NULL, NULL),
    ('603489', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603490', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603491', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603492', 'MAESTRO', 'DEBIT', NULL, 'TURKIYE GARANTI BANKASI, A.S.', 'TURKEY', '+902123181818', 'http://www.garanti.com.tr'),
    ('603493', 'TARJETA CENCOSUD', 'CREDIT', 'STANDARD', 'TARJETA CENCOSUD', 'ARGENTINA', NULL, NULL),
    ('603494', 'LOCAL BRAND', 'DEBIT', 'SILVER', 'PT. BANK MANDIRI (PERSERO) TBK.', 'INDONESIA', '+622152997777', 'https://bankmandiri.co.id'),
    ('603495', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603496', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603497', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603498', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603499', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603500', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603501', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603502', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603503', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603504', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603505', 'MAESTRO', 'DEBIT', NULL, 'VTB BANK (KAZAKHSTAN) SUBSIDIARY JOINT STOCK COMPANY', 'Kazakhstan', '+7 (727) 330-50-50', 'en.vtb-bank.kz'),
    ('603506', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603507', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603508', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603509', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603510', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603511', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603512', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603513', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603514', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603515', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603516', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603517', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603518', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603519', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603520', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603521', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603522', 'CABAL', 'CREDIT', NULL, 'CABAL', 'ARGENTINA', NULL, NULL),
    ('603523', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603524', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603525', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603526', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603527', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603528', 'MAESTRO', 'DEBIT', NULL, 'STAPLES CANADA (ISSUED BY CITI CARDS CANADA)', 'Canada', '877-360-8500', 'www.staples.ca/'),
    ('603529', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603530', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603531', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603532', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603533', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603534', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603535', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603536', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('603537', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do');

INSERT OR REPLACE INTO bins (bin, brand, type, category, issuer, country, bank_phone, bank_url) VALUES
    ('603538', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603539', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603540', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603541', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603542', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603543', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603544', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603545', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603546', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603547', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603548', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603549', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603550', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603551', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('603552', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603553', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603554', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603555', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'UNITED STATES', NULL, NULL),
    ('603556', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('603557', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603558', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603559', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603560', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603561', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603562', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603563', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603564', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603565', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603566', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603567', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603568', 'EBT', 'DEBIT', NULL, 'CITIBANK, N.A.', 'UNITED STATES', '+18003749700', 'https://www.citi.com'),
    ('603569', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603570', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603571', 'EBT', 'DEBIT', 'GIFT', 'CITIBANK USA, N.A.', 'UNITED STATES', '+18003749700', 'https://online.citibank.com'),
    ('603572', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603573', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603574', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603575', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603576', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603577', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603578', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603579', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603580', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603581', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603582', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603583', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603584', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603585', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603586', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603587', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603588', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603589', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603590', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603591', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603592', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603593', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603594', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603595', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603596', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603597', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603598', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603599', 'MAESTRO', 'DEBIT', NULL, 'CITIBANK USA, N.A.', 'United States', '1-800-950-5114', 'onlane.citi.com/US/login.do'),
    ('603600', 'MAESTRO', 'DEBIT', NULL, NULL, 'BRAZIL', NULL, NULL),
    ('603601', 'CHINA UNION PAY', 'DEBIT', NULL, 'HUISHANG BANK', 'CHINA', '+864008896588', 'http://www.hsbank.com.cn'),
    ('603602', 'MAESTRO', 'DEBIT', NULL, 'SHAOXING COMMERCIAL BANK', 'CHINA', '40000896528', 'http://www.sxccb.com'),
    ('603603', 'MAESTRO', 'DEBIT', NULL, NULL, 'CZECH REPUBLIC', NULL, NULL),
    ('603604', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603605', 'MAESTRO', 'DEBIT', NULL, 'BANK JATIM', 'INDONESIA', NULL, NULL),
    ('603606', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603607', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('603608', 'MAESTRO', 'DEBIT', 'PERSONAL', NULL, 'UNITED STATES', NULL, NULL),
    ('603609', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('603610', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603611', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603612', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603613', 'MAESTRO', 'DEBIT', 'PERSONAL', NULL, 'UNITED STATES', NULL, NULL),
    ('603614', 'MAESTRO', 'DEBIT', NULL, 'TURKIYE GARANTI BANKASI, A.S.', 'TURKEY', '+902123181818', 'http://www.garanti.com.tr'),
    ('603615', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('603616', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603617', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603618', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603619', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603620', 'EBT', 'DEBIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('603621', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603622', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603623', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603624', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('603625', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603626', 'CIRRUS', 'DEBIT', 'PERSONAL', NULL, 'UNITED STATES', NULL, NULL),
    ('603627', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603628', 'MAESTRO', 'DEBIT', 'GIFT', 'GIVEX CHAPTERS/INDIGO/COLES', 'CANADA', NULL, NULL),
    ('603629', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603630', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603631', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603632', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603633', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('603634', 'MAESTRO', 'DEBIT', 'PERSONAL', NULL, 'UNITED STATES', NULL, NULL),
    ('603635', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603636', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603637', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL);

INSERT OR REPLACE INTO bins (bin, brand, type, category, issuer, country, bank_phone, bank_url) VALUES
    ('603638', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603639', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603640', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603641', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603642', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603643', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603644', 'MAESTRO', 'DEBIT', 'PERSONAL', NULL, 'UNITED STATES', NULL, NULL),
    ('603645', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603646', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603647', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603648', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603649', 'MAESTRO', 'DEBIT', NULL, 'YAPI VE KREDI BANKASI, A.S.', 'TURKEY', '+904440444', 'http://www.yapikredi.com.tr'),
    ('603650', 'MAESTRO', 'DEBIT', NULL, 'T. GARANTI BANKASI A.S', 'TURKEY', NULL, NULL),
    ('603651', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603652', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603653', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603654', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603655', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603656', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603657', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603658', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603659', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603660', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603661', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603662', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603663', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603664', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603665', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603666', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603667', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603668', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603669', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603670', 'MAESTRO', 'DEBIT', 'PERSONAL', NULL, 'UNITED STATES', NULL, NULL),
    ('603671', 'MAESTRO', 'DEBIT', 'PERSONAL', NULL, 'UNITED STATES', NULL, NULL),
    ('603672', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('603673', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('603674', 'MAESTRO', 'DEBIT', 'PERSONAL', NULL, 'UNITED STATES', NULL, NULL),
    ('603675', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603676', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603677', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603678', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603679', 'EBT', 'DEBIT', 'STANDARD', 'WELLS FARGO BANK, N.A.', 'UNITED STATES', '+18006424720', 'https://www.wellsfargo.com'),
    ('603680', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('603681', 'MAESTRO', 'DEBIT', 'STANDARD', 'VALE ELECTRONICO ACCOR', 'MEXICO', NULL, NULL),
    ('603682', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('603683', 'MAESTRO', 'DEBIT', 'PERSONAL', NULL, 'UNITED STATES', NULL, NULL),
    ('603684', 'MAESTRO', 'DEBIT', 'PERSONAL', NULL, 'UNITED STATES', NULL, NULL),
    ('603685', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603686', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603687', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603688', 'ELO', 'DEBIT', NULL, NULL, 'BRAZIL', NULL, NULL),
    ('603689', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('603690', 'ELO', 'DEBIT', NULL, NULL, 'BRAZIL', NULL, NULL),
    ('603691', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603692', 'MAESTRO', 'DEBIT', NULL, 'STOCKMANN DEPARTMENT STORE MASTERCARD, ISSUED BY NORDEA(FINlanD)', 'Finland', '0200 70000', 'www.nordea.fi/en/personal/our-services/credit-payment-cards/stockmann-mastercard.html'),
    ('603693', 'MAESTRO', 'DEBIT', 'PERSONAL', NULL, 'UNITED STATES', NULL, NULL),
    ('603694', 'CHINA UNION PAY', 'DEBIT', NULL, 'CHANGSU RURAL COMMERCIAL BANK', 'CHINA', '+86512962000', 'http://www.csrcbank.com'),
    ('603695', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603696', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('603697', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603698', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603699', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603700', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603701', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603702', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603703', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603704', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('603705', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603706', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603707', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603708', 'CHINA UNION PAY', 'DEBIT', NULL, 'DALIAN CITY COMMERCIAL BANK', 'CHINA', '+864006640099', 'http://www.bankofdl.com'),
    ('603709', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603710', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603711', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603712', 'EBT', 'DEBIT', 'STANDARD', 'WELLS FARGO BANK, N.A.', 'UNITED STATES', '+18006424720', 'https://www.wellsfargo.com'),
    ('603713', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603714', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603715', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603716', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603717', 'MAESTRO', 'DEBIT', NULL, 'UNIBANCO - UNIAO DE BANCOS BRASILEIROS, S.A.', 'Panama', '297-6000', 'www.unibank.com.pa'),
    ('603718', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603719', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603720', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603721', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603722', 'MAESTRO', 'DEBIT', 'PERSONAL', 'U.S. BANK, N.A.', 'UNITED STATES', '+18008722657', 'https://www.usbank.com'),
    ('603723', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603724', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603725', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603726', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603727', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603728', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603729', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603730', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603731', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603732', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603733', 'MAESTRO', 'DEBIT', NULL, NULL, 'PAKISTAN', NULL, NULL),
    ('603734', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603735', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603736', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603737', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL);

INSERT OR REPLACE INTO bins (bin, brand, type, category, issuer, country, bank_phone, bank_url) VALUES
    ('603738', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603739', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603740', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('603741', 'MAESTRO', 'DEBIT', 'PERSONAL', NULL, 'UNITED STATES', NULL, NULL),
    ('603742', 'MAESTRO', 'DEBIT', NULL, 'UNIBANCO - UNIAO DE BANCOS BRASILEIROS, S.A.', 'Panama', '297-6000', 'www.unibank.com.pa'),
    ('603743', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603744', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603745', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603746', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603747', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603748', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603749', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603750', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('603751', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603752', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603753', 'EBT', 'DEBIT', 'GIFT', 'MCDONALD''S', 'UNITED STATES', '+18002446227', 'http://www.mcdonalds.com'),
    ('603754', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603755', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603756', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603757', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603758', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603759', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603760', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603761', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603762', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603763', 'MAESTRO', 'DEBIT', NULL, NULL, 'POLAND', NULL, NULL),
    ('603764', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603765', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603766', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603767', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603768', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603769', 'MAESTRO', 'DEBIT', NULL, 'BANK SADERAT IRAN', 'IRAN', '+971 46 035555', 'www.banksaderat.ae/'),
    ('603770', 'MAESTRO', 'DEBIT', NULL, NULL, 'RUSSIAN FEDERATION', NULL, NULL),
    ('603771', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603772', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603773', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603774', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603775', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603776', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603777', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603778', 'MAESTRO', 'DEBIT', 'STANDARD', 'GE CAPITAL BANK', 'MEXICO', NULL, NULL),
    ('603779', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603780', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('603781', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603782', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603783', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603784', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603785', 'LOCAL BRAND', 'CREDIT', NULL, 'FIRSTRAND BANK, LTD.', 'SOUTH AFRICA', '+27112821808', 'http://www.firstrand.co.za'),
    ('603786', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603787', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603788', 'MAESTRO', 'DEBIT', 'Q-CASH', 'BANK ASIA, LTD.', 'BANGLADESH', '+88027110042', 'http://www.bankasia-bd.com'),
    ('603789', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603790', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603791', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603792', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603793', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603794', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('603795', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('603796', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603797', 'MAESTRO', 'DEBIT', NULL, 'YAPI VE KREDI BANKASI, A.S.', 'TURKEY', NULL, 'http://www.yapikredi.com.tr'),
    ('603798', 'CIRRUS', 'DEBIT', NULL, 'KIWIBANK, LTD.', 'NEW ZEALAND', '+64800113355', 'http://www.kiwibank.co.nz'),
    ('603799', 'LOCAL BRAND', 'DEBIT', NULL, 'MELLI BANK', 'IRAN, ISLAMIC REPUBLIC OF', NULL, NULL),
    ('603800', 'EBT', 'DEBIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('603801', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603802', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603803', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603804', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603805', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603806', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603807', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603808', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603809', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603810', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603811', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603812', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603813', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603814', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603815', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603816', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603817', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603818', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603819', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603820', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603821', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603822', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603823', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603824', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603825', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603826', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603827', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603828', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603829', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('603830', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603831', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603832', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603833', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603834', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603835', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603836', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL),
    ('603837', 'EBT', 'DEBIT', 'PROPRIETARY', NULL, 'UNITED STATES', NULL, NULL);

COMMIT;
