-- Batch 436 - 500 records
BEGIN TRANSACTION;

INSERT OR REPLACE INTO bins (bin, brand, type, category, issuer, country, bank_phone, bank_url) VALUES
    ('482838', 'VISA', 'CREDIT', 'TRADITIONAL', 'LOCO CREDIT UNION', 'UNITED STATES', NULL, NULL),
    ('482839', 'VISA', 'CREDIT', 'BUSINESS', 'FIRST CENTRAL CREDIT UNION', 'UNITED STATES', '+18007807101', 'https://www.firstcentralcu.com'),
    ('482840', 'VISA', 'CREDIT', 'TRADITIONAL', 'PEOPLES CREDIT UNION', 'UNITED STATES', NULL, NULL),
    ('482841', 'VISA', 'CREDIT', 'BUSINESS', 'THREAD BANK', 'UNITED STATES', NULL, NULL),
    ('482842', 'VISA', 'CREDIT', 'TRADITIONAL', 'CAPITAL ONE, NATIONAL ASSOCIATION', 'UNITED STATES', NULL, NULL),
    ('482843', 'VISA', 'CREDIT', 'TRADITIONAL', 'APL FEDERAL CREDIT UNION', 'UNITED STATES', '+14437785250', 'https://www.aplfcu.org'),
    ('482844', 'VISA', 'CREDIT', NULL, 'WELLS FARGO BANK, N.A.', 'UNITED STATES', '+18008693557', 'https://www.wellsfargo.com'),
    ('482845', 'VISA', 'CREDIT', NULL, 'WELLS FARGO BANK, N.A.', 'UNITED STATES', '+18008693557', 'https://www.wellsfargo.com'),
    ('482846', 'VISA', 'CREDIT', NULL, 'WELLS FARGO BANK, N.A.', 'UNITED STATES', '+18008693557', 'https://www.wellsfargo.com'),
    ('482847', 'VISA', 'CREDIT', 'TRADITIONAL', 'MRV BANKS', 'UNITED STATES', '+15738838222', 'https://www.mrvbanks.com'),
    ('482848', 'VISA', 'CREDIT', 'TRADITIONAL', 'WASHINGTON FEDERAL BANK', 'UNITED STATES', NULL, 'https://www.wafdbank.com'),
    ('482849', 'VISA', 'CREDIT', 'PLATINUM', 'MOUNTAIN AMERICA F.C.U.', 'United States', '1-800-748-4302', 'www.macu.com'),
    ('482850', 'VISA', 'DEBIT', 'CLASSIC', 'WACHOVIA BANK, N.A.', 'United States', NULL, NULL),
    ('482851', 'VISA', 'DEBIT', 'CLASSIC', 'WACHOVIA BANK, N.A.', 'United States', NULL, NULL),
    ('482852', 'VISA', 'DEBIT', 'CLASSIC', 'WACHOVIA BANK, N.A.', 'United States', NULL, NULL),
    ('482853', 'VISA', 'DEBIT', 'CLASSIC', 'WACHOVIA BANK, N.A.', 'United States', NULL, NULL),
    ('482854', 'VISA', 'DEBIT', 'CLASSIC', 'WACHOVIA BANK, N.A.', 'United States', NULL, NULL),
    ('482855', 'VISA', 'DEBIT', 'CLASSIC', 'WACHOVIA BANK, N.A.', 'United States', NULL, NULL),
    ('482856', 'VISA', 'DEBIT', 'CLASSIC', 'WACHOVIA BANK, N.A.', 'United States', NULL, NULL),
    ('482857', 'VISA', 'DEBIT', 'CLASSIC', 'WACHOVIA BANK, N.A.', 'United States', NULL, NULL),
    ('482858', 'VISA', 'DEBIT', 'CLASSIC', 'WELLS FARGO BANK, N.A.', 'UNITED STATES', '+18008693557', 'https://www.wellsfargo.com'),
    ('482859', 'VISA', 'CREDIT', NULL, 'WELLS FARGO BANK, N.A.', 'UNITED STATES', '+18008693557', 'https://www.wellsfargo.com'),
    ('482860', 'VISA', 'DEBIT', 'CLASSIC', 'WACHOVIA BANK, N.A.', 'United States', NULL, NULL),
    ('482861', 'VISA', 'DEBIT', 'CLASSIC', 'WACHOVIA BANK, N.A.', 'United States', NULL, NULL),
    ('482862', 'VISA', 'DEBIT', 'CLASSIC', 'WACHOVIA BANK, N.A.', 'United States', NULL, NULL),
    ('482863', 'VISA', 'DEBIT', 'CLASSIC', 'WACHOVIA BANK, N.A.', 'United States', NULL, NULL),
    ('482864', 'VISA', 'DEBIT', 'CLASSIC', 'WACHOVIA BANK, N.A.', 'United States', NULL, NULL),
    ('482865', 'VISA', 'DEBIT', 'CLASSIC', 'WACHOVIA BANK, N.A.', 'United States', NULL, NULL),
    ('482866', 'VISA', 'DEBIT', 'CLASSIC', 'WACHOVIA BANK, N.A.', 'United States', NULL, NULL),
    ('482867', 'VISA', 'DEBIT', 'CLASSIC', 'WELLS FARGO BANK, N.A.', 'UNITED STATES', '+18008693557', 'https://www.wellsfargo.com'),
    ('482868', 'VISA', 'DEBIT', 'CLASSIC', 'WELLS FARGO BANK, N.A.', 'UNITED STATES', '+18008693557', 'https://www.wellsfargo.com'),
    ('482869', 'VISA', 'DEBIT', 'CLASSIC', 'WELLS FARGO BANK, N.A.', 'UNITED STATES', '+18008693557', 'https://www.wellsfargo.com'),
    ('482870', 'VISA', 'DEBIT', 'CLASSIC', 'WELLS FARGO BANK, N.A.', 'UNITED STATES', '+18008693557', 'https://www.wellsfargo.com'),
    ('482871', 'VISA', 'DEBIT', 'CLASSIC', 'SANTANDER UK PLC', 'UNITED KINGDOM', '+448003899905', 'http://www.santander.co.uk'),
    ('482872', 'VISA', 'CREDIT', 'CLASSIC', 'NATIONWIDE BUILDING SOCIETY', 'UNITED KINGDOM', '+448000556611', 'http://www.nationwide.co.uk'),
    ('482873', 'VISA', 'CREDIT', 'GOLD', 'NATIONWIDE BUILDING SOCIETY', 'UNITED KINGDOM', '+448000556611', 'http://www.nationwide.co.uk'),
    ('482874', 'VISA', 'DEBIT', 'CLASSIC', 'NATIONWIDE BUILDING SOCIETY', 'UNITED KINGDOM', '+448000556611', 'http://www.nationwide.co.uk'),
    ('482875', 'VISA', 'CREDIT', 'TRADITIONAL', 'BANK FUND STAFF FEDERAL CREDIT UNION', 'UNITED STATES', NULL, NULL),
    ('482876', 'VISA', 'DEBIT', 'PREMIER', 'WACHOVIA BANK, N.A.', 'United States', NULL, NULL),
    ('482877', 'VISA', 'DEBIT', 'BUSINESS', 'WACHOVIA BANK, N.A.', 'United States', NULL, NULL),
    ('482878', 'VISA', 'DEBIT', 'CLASSIC', 'WELLS FARGO BANK, N.A.', 'UNITED STATES', '+18008693557', 'https://www.wellsfargo.com'),
    ('482879', 'VISA', 'DEBIT', 'BUSINESS', 'WACHOVIA BANK, N.A.', 'United States', NULL, NULL),
    ('482880', 'VISA', 'DEBIT', 'BUSINESS', 'WELLS FARGO BANK, N.A.', 'UNITED STATES', '+18008693557', 'https://www.wellsfargo.com'),
    ('482881', 'VISA', 'DEBIT', 'CLASSIC', 'WACHOVIA BANK, N.A.', 'United States', NULL, NULL),
    ('482882', 'VISA', 'DEBIT', 'BUSINESS', 'WELLS FARGO BANK, N.A.', 'UNITED STATES', '+18008693557', 'https://www.wellsfargo.com'),
    ('482883', 'VISA', 'CREDIT', 'CLASSIC', 'CUSCAL, LTD.', 'AUSTRALIA', NULL, 'https://www.cuscal.com.au'),
    ('482884', 'VISA', 'CREDIT', NULL, 'WELLS FARGO BANK, N.A.', 'UNITED STATES', '+18008693557', 'https://www.wellsfargo.com'),
    ('482885', 'VISA', 'DEBIT', 'CLASSIC', 'TEACHERS MUTUAL BANK, LTD.', 'AUSTRALIA', NULL, NULL),
    ('482886', 'VISA', 'CREDIT', NULL, 'WELLS FARGO BANK, N.A.', 'UNITED STATES', '+18008693557', 'https://www.wellsfargo.com'),
    ('482887', 'VISA', 'DEBIT', 'CLASSIC', 'HERITAGE AND PEOPLE''S CHOICE, LTD.', 'AUSTRALIA', NULL, NULL),
    ('482888', 'VISA', 'DEBIT', 'PREPAID BUSINESS', 'CREDIT SAISON CO., LTD.', 'JAPAN', '+81339882111', 'http://corporate.saisoncard.co.jp'),
    ('482889', 'VISA', 'CREDIT', NULL, 'WELLS FARGO BANK, N.A.', 'UNITED STATES', '+18008693557', 'https://www.wellsfargo.com'),
    ('482890', 'VISA', 'DEBIT', 'CLASSIC', 'WACHOVIA BANK, N.A.', 'United States', NULL, NULL),
    ('482891', 'VISA', 'DEBIT', 'CLASSIC', 'WELLS FARGO BANK, N.A.', 'UNITED STATES', '+18008693557', 'https://www.wellsfargo.com'),
    ('482892', 'VISA', 'DEBIT', 'CLASSIC', 'CARVER FEDERAL SAVINGS BANK', 'UNITED STATES', '+17182302900', 'https://www.carverbank.com'),
    ('482893', 'VISA', 'DEBIT', 'BUSINESS', 'CARVER FEDERAL SAVINGS BANK', 'UNITED STATES', '+17182302900', 'https://www.carverbank.com'),
    ('482894', 'VISA', 'DEBIT', 'CLASSIC', 'WELLS FARGO BANK, N.A.', 'UNITED STATES', '+18008693557', 'https://www.wellsfargo.com'),
    ('482895', 'VISA', 'DEBIT', 'CLASSIC', 'INDUSIND BANK, LTD.', 'INDIA', NULL, 'http://www.indusind.com'),
    ('482896', 'VISA', 'DEBIT', 'CLASSIC', 'WELLS FARGO BANK, N.A.', 'UNITED STATES', '+18008693557', 'https://www.wellsfargo.com'),
    ('482897', 'VISA', 'DEBIT', 'CLASSIC', 'WACHOVIA BANK, N.A.', 'United States', NULL, NULL),
    ('482898', 'VISA', 'DEBIT', 'CLASSIC', 'WELLS FARGO BANK, N.A.', 'UNITED STATES', '+18008693557', 'https://www.wellsfargo.com'),
    ('482899', 'VISA', 'DEBIT', 'CLASSIC', 'PUGET SOUND COOPERATIVE CREDIT UNION', 'UNITED STATES', '+18002731550', 'https://www.psccu.org'),
    ('482900', 'VISA', 'CREDIT', 'CLASSIC', 'WELLS FARGO BANK, N.A.', 'United States', NULL, NULL),
    ('482901', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482902', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482903', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482904', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482905', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482906', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482907', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482908', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482909', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482910', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482911', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482912', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482913', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482914', 'VISA', 'DEBIT', 'CLASSIC', 'TRUIST BANK', 'UNITED STATES', '+18444878478', 'https://www.truist.com'),
    ('482915', 'VISA', 'CREDIT', 'CLASSIC', 'UNICRE - INSTITUICAO FINANCEIRA DE CREDITO, S.A.', 'PORTUGAL', NULL, 'http://www.unicre.pt'),
    ('482916', 'VISA', 'CREDIT', 'BUSINESS', 'BANK OF SHANGHAI', 'CHINA', '95594', 'http://www.bosc.cn'),
    ('482917', 'VISA', 'CREDIT', 'CLASSIC', 'C. HOARE & CO.', 'UNITED KINGDOM', NULL, NULL),
    ('482918', 'VISA', 'CREDIT', 'CLASSIC', 'C. HOARE & CO.', 'UNITED KINGDOM', NULL, NULL),
    ('482919', 'VISA', 'DEBIT', 'CLASSIC', 'MKB BANK ZRT.', 'HUNGARY', '327-8600', 'http://www.mkb.hu'),
    ('482920', 'VISA', 'DEBIT', 'CLASSIC', 'AHLI UNITED BANK (UK) PLC', 'UNITED KINGDOM', NULL, NULL),
    ('482921', 'VISA', 'DEBIT', 'CLASSIC', 'ICBA BANCARD', 'United States', '800-242-4770', 'www.icba.org/bancard/homepage'),
    ('482922', 'VISA', 'DEBIT', 'CLASSIC', 'FIRST INTERSTATE BANK', 'United States', '855-342-3400', 'www.firstinterstatebank.com'),
    ('482923', 'VISA', 'DEBIT', 'CLASSIC', 'VISTA BANK (ROMANIA), S.A.', 'ROMANIA', NULL, NULL),
    ('482924', 'VISA', 'DEBIT', 'CLASSIC', 'MAGNOLIA STATE BANK', 'United States', '1-855-BANKMAG (226-5624)', 'www.bankmagnolia.com'),
    ('482925', 'VISA', 'DEBIT', 'BUSINESS', 'AMERICA''S CREDIT UNION', 'UNITED STATES', '+19724945328', 'https://www.americascu.org'),
    ('482926', 'VISA', 'CREDIT', 'PLATINUM', 'SAN FRANCISCO F.C.U.', 'United States', '415.775.5377', 'www.sanfranciscofcu.com/'),
    ('482927', 'VISA', 'CREDIT', 'CLASSIC', 'BENTON COUNTY SCHOOLS C.U.', 'United States', '888-241-2510', 'https://bcscu.org/'),
    ('482928', 'VISA', 'CREDIT', 'CLASSIC', 'KINA SECURITIES, LTD.', 'PAPUA NEW GUINEA', NULL, NULL),
    ('482929', 'VISA', 'CREDIT', 'CLASSIC', 'RIVERMARK COMMUNITY C.U.', 'United States', '503.626.6600', 'www.rivermarkcu.org/'),
    ('482930', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482931', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482932', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482933', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482934', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482935', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482936', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482937', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL);

INSERT OR REPLACE INTO bins (bin, brand, type, category, issuer, country, bank_phone, bank_url) VALUES
    ('482938', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482939', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482940', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482941', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482942', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482943', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482944', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482945', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482946', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482947', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482948', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482949', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482950', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482951', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482952', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482953', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482954', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482955', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482956', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482957', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482958', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482959', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482960', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482961', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482962', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482963', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482964', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482965', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482966', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482967', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482968', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482969', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482970', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482971', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482972', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482973', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482974', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482975', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482976', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482977', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482978', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482979', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482980', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482981', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482982', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482983', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482984', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482985', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482986', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482987', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482988', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482989', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482990', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482991', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482992', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482993', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482994', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482995', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482996', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482997', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482998', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('482999', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483000', 'VISA', 'CREDIT', 'CLASSIC', 'FIA CARD SERVICES, N.A.', 'United States', NULL, NULL),
    ('483001', 'VISA', 'DEBIT', 'CLASSIC', 'BANCO INDUSTRIAL, S.A.', 'Guatemala', 'PBX:1717', 'www.corporacionbi.com/gt/bancoindustrial/inicio'),
    ('483002', 'VISA', 'DEBIT', 'PLATINUM', 'VISA ARGENTINA, S.A.', 'Argentina', '0800-666-0171', 'www.visa.com.ar/'),
    ('483003', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483004', 'VISA', 'DEBIT', NULL, 'BORGUN HF', 'ICELAND', NULL, NULL),
    ('483005', 'VISA', 'DEBIT', 'ELECTRON', 'VISA JORDAN CARD SERVICES', 'Jordan', '1-880-0000 / 888-557-4442', 'jo.visamiddleeast.com'),
    ('483006', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483007', 'VISA', 'DEBIT', 'ELECTRON', 'PIRAEUS BANK ROMANIA', 'ROMANIA', '+40800801802', 'http://www.pireusbank.ro'),
    ('483008', 'VISA', 'DEBIT', 'PREPAID ELECTRON', 'NEXI PAYMENTS S.P.A.', 'ITALY', '+18004736896', 'https://www.nexi.it'),
    ('483009', 'VISA', 'DEBIT', 'PREPAID CLASSIC', 'ARAB PAYMENT SERVICES', 'IRAQ', NULL, NULL),
    ('483010', 'VISA', 'DEBIT', NULL, 'UNITED SAUDI COMMERCIAL BANK', 'United States', '(966) 1-4784200', NULL),
    ('483011', 'VISA', 'DEBIT', NULL, 'UNITED SAUDI COMMERCIAL BANK', 'United States', '(966) 1-4784200', NULL),
    ('483012', 'VISA', 'DEBIT', NULL, 'UNITED SAUDI COMMERCIAL BANK', 'United States', '(966) 1-4784200', NULL),
    ('483013', 'VISA', 'CREDIT', 'CLASSIC', 'BURGAN BANK', 'TURKEY', NULL, NULL),
    ('483014', 'VISA', 'DEBIT', 'CLASSIC', 'CARIBBEAN CREDIT CARD CORPORATION', 'Antigua and Barbuda', '(869) 465 3700', 'https://www.4csonlane.com/'),
    ('483015', 'VISA', 'DEBIT', 'CLASSIC', 'VISA COLOMBIA', 'Colombia', '01-800-912-2066', 'www.visa.com.co'),
    ('483016', 'VISA', 'DEBIT', 'CLASSIC', 'TT HELlanIC POSTBANK', 'Greece', NULL, NULL),
    ('483017', 'VISA', 'CREDIT', NULL, 'PAYLIFE BANK GMBH', 'AUSTRIA', '+43599060', 'http://www.paylife.at'),
    ('483018', 'VISA', 'CREDIT', 'CLASSIC', 'WIELKOPOLSKI BANK SPOLDZIELCZY', 'Poland', '618 512 512', 'www.neobank.pl/portal/start'),
    ('483019', 'VISA', 'CREDIT', 'PLATINUM', 'MERCANTILE BANK, LTD.', 'BANGLADESH', NULL, 'http://www.mercantile.co.za'),
    ('483020', 'VISA', 'DEBIT', 'CLASSIC', 'VISA ARGENTINA, S.A.', 'Argentina', '0800-666-0171', 'www.visa.com.ar/'),
    ('483021', 'VISA', 'DEBIT', 'CLASSIC', 'JSC STATE SAVINGS BANK OF UKRAINE (JSC OSCHADBANK)', 'UKRAINE', '+380443630133', 'http://www.oschadnybank.com'),
    ('483022', 'VISA', 'CREDIT', 'TRADITIONAL', 'BANK FUND STAFF FEDERAL CREDIT UNION', 'UNITED STATES', NULL, NULL),
    ('483023', 'VISA', 'CREDIT', 'TRADITIONAL', 'BANK FUND STAFF FEDERAL CREDIT UNION', 'UNITED STATES', NULL, NULL),
    ('483024', 'VISA', 'CREDIT', 'CLASSIC', 'BANK FUND STAFF FEDERAL CREDIT UNION', 'UNITED STATES', NULL, NULL),
    ('483025', 'VISA', 'CREDIT', 'TRADITIONAL', 'KEYPOINT CREDIT UNION', 'UNITED STATES', '+18882553637', 'https://kpcu.com'),
    ('483026', 'VISA', 'DEBIT', 'PLATINUM', 'UNITED OVERSEAS BANK, LTD.', 'SINGAPORE', '+6518002222121', 'http://www.uob.com.sg'),
    ('483027', 'VISA', 'DEBIT', 'CLASSIC', 'CITIGROUP PTY, LTD.', 'AUSTRALIA', '+61282250615', 'http://www.citibank.com.au'),
    ('483028', 'VISA', 'DEBIT', 'BUSINESS', 'AUSTRALIA AND NEW ZEALAND BANKING GROUP, LTD.', 'AUSTRALIA', NULL, NULL),
    ('483029', 'VISA', 'DEBIT', 'CLASSIC', 'HSBC MEXICO S.A., INSTITUCION DE BANCA MULTIPLE, GRUPO FINAN', 'MEXICO', '5721- 3390', 'http://www.hsbc.com.mx'),
    ('483030', 'VISA', 'DEBIT', 'PLATINUM', 'HSBC', 'Mexico', NULL, NULL),
    ('483031', 'VISA', 'DEBIT', 'CLASSIC', 'BANCO DE CREDITO E INVERSIONES', 'CHILE', '+566008242424', 'http://www.bci.cl'),
    ('483032', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483033', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483034', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483035', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483036', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483037', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL);

INSERT OR REPLACE INTO bins (bin, brand, type, category, issuer, country, bank_phone, bank_url) VALUES
    ('483038', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483039', 'VISA', 'DEBIT', 'CLASSIC', 'INTERBANK - BANCO INTERNACIONAL DEL PERU', 'Peru', '311 9000', 'https://interbank.pe/'),
    ('483040', 'VISA', 'CREDIT', 'CLASSIC', 'BANCO BRADESCO, S.A.', 'BRAZIL', '+5540020022', 'http://www.bradesco.com.br'),
    ('483041', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483042', 'VISA', 'CREDIT', 'PLATINUM', 'WIRECARD BANK AG', 'Brazil', NULL, 'www.wirecardbank.com'),
    ('483043', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483044', 'VISA', 'CREDIT', NULL, 'REDECARD, S.A.', 'BRAZIL', NULL, 'http://www.redecard.com.br'),
    ('483045', 'VISA', 'DEBIT', 'ELECTRON', 'BANCA SAMMARINESE DI INVESTIMENTO S.P.A.', 'San Marino', '+378 0549 940900', 'www.bsi.sm/en/'),
    ('483046', 'VISA', 'DEBIT', 'ELECTRON', 'WIELKOPOLSKI BANK SPOLDZIELCZY', 'Poland', '618 512 512', 'www.neobank.pl/portal/start'),
    ('483047', 'VISA', 'DEBIT', 'ELECTRON', 'WIELKOPOLSKI BANK SPOLDZIELCZY', 'Poland', '618 512 512', 'www.neobank.pl/portal/start'),
    ('483048', 'VISA', 'DEBIT', NULL, 'RAIFFEISEN BANK ZRT.', 'HUNGARY', '+3680488588', 'http://www.raiffeisen.hu'),
    ('483049', 'VISA', 'DEBIT', 'CORPORATE T&E', 'BANCO DE LA NACION ARGENTINA', 'Argentina', '0810-666-4444', 'http://www.bna.com.ar'),
    ('483050', 'VISA', 'CREDIT', NULL, 'HSBC BANK PLC', 'UNITED KINGDOM', NULL, 'http://www.hsbc.co.uk'),
    ('483051', 'VISA', 'DEBIT', 'ELECTRON', 'BANCA MONTE DEI PASCHI DI SIENA S.P.A.', 'ITALY', NULL, 'http://english.mps.it'),
    ('483052', 'VISA', 'CREDIT', 'CLASSIC', 'COPAYMENT DE MEXICO S.A.P.I. DE C.V.', 'MEXICO', NULL, NULL),
    ('483053', 'VISA', 'DEBIT', 'CLASSIC', 'KOMERCNI BANKA, A.S.', 'CZECH REPUBLIC', NULL, 'http://www.kb.cz'),
    ('483054', 'VISA', 'CREDIT', 'CORPORATE T&E', 'INTESA SANPAOLO S.P.A.', 'ITALY', '+39064462031', 'http://www.intesasanpaolo.com'),
    ('483055', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483056', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483057', 'VISA', 'DEBIT', 'CLASSIC', 'ASOCIACION POPULAR DE AHORROS Y PRESTAMOS', 'DOMINICAN REPUBLIC', '809.687.APAP (2727)', 'http://www.apap.com.do'),
    ('483058', 'VISA', 'CREDIT', 'CLASSIC', 'RESURS BANK AB', 'NORWAY', '+4722563733', 'https://www.resursbank.no'),
    ('483059', 'VISA', 'CREDIT', NULL, 'NORDEA BANK DANMARK A/S', 'DENMARK', '(+45) 33-33-33-33', 'http://www.nordea.com'),
    ('483060', 'VISA', 'DEBIT', NULL, 'NORDEA BANK FINLAND PLC', 'ESTONIA', '+35820070000', 'http://www.nordea.com'),
    ('483061', 'VISA', 'DEBIT', NULL, 'NORDEA BANK FINLAND PLC', 'LATVIA', NULL, 'http://www.nordea.com'),
    ('483062', 'VISA', 'DEBIT', NULL, 'NORDEA BANK FINLAND PLC', 'LITHUANIA', NULL, 'http://www.nordea.com'),
    ('483063', 'VISA', 'DEBIT', 'PREPAID BUSINESS', 'INTESA SANPAOLO S.P.A.', 'ITALY', '+39064462031', 'http://www.intesasanpaolo.com'),
    ('483064', 'VISA', 'CREDIT', NULL, 'NORDEA BANK ABP', 'SWEDEN', '+4686147000', 'http://www.nordea.com'),
    ('483065', 'VISA', 'CREDIT', NULL, 'NORDEA BANK NORGE ASA HK', 'NORWAY', '+4723206001', 'http://www.nordea.no'),
    ('483066', 'VISA', 'CREDIT', 'CLASSIC', 'BANCO PANAMERICANO, S.A.', 'Brazil', '0800-888-0101', 'www.bancopan.com.br'),
    ('483067', 'VISA', 'CREDIT', 'PLATINUM', 'WIRECARD BANK AG', 'Brazil', NULL, 'www.wirecardbank.com'),
    ('483068', 'VISA', 'DEBIT', 'CLASSIC', 'VALORES INTERNACIONALES, S.A.', 'Guatemala', NULL, NULL),
    ('483069', 'VISA', 'DEBIT', 'PROPRIETARY', 'YORKSHIRE BANK', 'United Kingdom', '0800 678 3320', 'secure.ybonlane.co.uk'),
    ('483070', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483071', 'VISA', 'DEBIT', 'CLASSIC', 'LOGBERG TRUST CORP., LTD.', 'Turks and Caicos Islands', '649-946-4261', NULL),
    ('483072', 'VISA', 'CREDIT', NULL, 'B+S CARD SERVICE GMBH', 'GERMANY', '+496966305529', 'https://www.bspayone.com'),
    ('483073', 'VISA', 'DEBIT', 'CLASSIC', 'BANCO BAC SAN JOSE, S.A.', 'COSTA RICA', NULL, 'http://www.bac.net'),
    ('483074', 'VISA', 'DEBIT', NULL, 'BANK OF AMERICA, N.A.', 'VIRGIN ISLANDS, U.S.', NULL, 'http://www.bankofamerica.com'),
    ('483075', 'VISA', 'DEBIT', 'CLASSIC', 'BANCO DE OCCIDENTE, S.A.', 'Honduras', '2290-7000', 'www.bancocci.hn'),
    ('483076', 'VISA', 'DEBIT', NULL, 'BANCO LAFISE BANCENTRO, S.A.', 'NICARAGUA', '+50522782777 / +50522780803', 'http://www.bancolafise.com.ni'),
    ('483077', 'VISA', 'CREDIT', 'CLASSIC', 'WIRECARD BANK AG', 'Brazil', NULL, 'www.wirecardbank.com'),
    ('483078', 'VISA', 'DEBIT', NULL, 'MAGYAR TAKAREKSZOVETKEZETI BANK ZRT.', 'HUNGARY', NULL, NULL),
    ('483079', 'VISA', 'DEBIT', 'PLATINUM', 'VALES INTERCONTINENTALES, S.A.', 'Costa Rica', NULL, NULL),
    ('483080', 'VISA', 'CREDIT', NULL, 'VISA COLOMBIA', 'United States', '(800) 396-9665', 'www.visa.com.co'),
    ('483081', 'VISA', 'DEBIT', 'PREPAID', 'CITIBANK EUROPE PLC', 'Slovakia', '0800 00 55 00', 'www.citibank.co.uk/citicentre'),
    ('483082', 'VISA', 'DEBIT', 'VPAY', 'LANDESBANK SAAR', 'GERMANY', '+4968138301', 'http://www.saarlb.de'),
    ('483083', 'VISA', 'DEBIT', NULL, 'NEXTEBANK, S.A.', 'ROMANIA', NULL, NULL),
    ('483084', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483085', 'VISA', 'CREDIT', 'CLASSIC', 'BANCO ITAUCARD, S.A.', 'Brazil', NULL, NULL),
    ('483086', 'VISA', 'DEBIT', 'PLATINUM', 'KOTAK MAHINDRA BANK, LTD.', 'INDIA', NULL, 'http://www.kotak.com'),
    ('483087', 'VISA', 'CREDIT', 'CLASSIC', 'RIAS S.R.L. (BANCOMAT)', 'Uruguay', NULL, NULL),
    ('483088', 'VISA', 'DEBIT', 'PLATINUM', 'BANCO BRADESCO, S.A.', 'BRAZIL', NULL, 'http://www.bradesco.com.br'),
    ('483089', 'VISA', 'CREDIT', 'CLASSIC', '**PROVISIONAL BID - VPP10460 - FFT** LEYDEK, S.A.', 'URUGUAY', NULL, NULL),
    ('483090', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483091', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483092', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483093', 'VISA', 'CREDIT', 'INFINITE', 'VALES INTERCONTINENTALES, S.A.', 'Costa Rica', NULL, NULL),
    ('483094', 'VISA', 'DEBIT', NULL, 'PROCARD, S.A.', 'PARAGUAY', '+595214167000', 'http://www.procard.com.py'),
    ('483095', 'VISA', 'CREDIT', 'CLASSIC', 'ASOCIACION LA VEGA REAL DE AHORROS Y PRESTAMOS', 'Dominican Republic', '809 573 2315', 'alaver.com.do'),
    ('483096', 'VISA', 'CREDIT', 'CLASSIC', 'BANCO ITAUCARD, S.A.', 'Brazil', NULL, NULL),
    ('483097', 'VISA', 'CREDIT', 'PREMIER', 'BANCO ITAUCARD, S.A.', 'Brazil', NULL, NULL),
    ('483098', 'VISA', 'CREDIT', 'PLATINUM', 'BANCO ITAUCARD, S.A.', 'Brazil', NULL, NULL),
    ('483099', 'VISA', 'DEBIT', 'PREPAID', 'CITIBANK EUROPE PLC', 'CZECHIA', '-2270', 'www.citigroup.com'),
    ('483100', 'VISA', 'CREDIT', 'CLASSIC', 'NATIONAL CITY BANK', 'United States', NULL, NULL),
    ('483101', 'VISA', 'CREDIT', NULL, 'VISA COLOMBIA', 'United States', '(800) 396-9665', 'www.visa.com.co'),
    ('483102', 'VISA', 'CREDIT', NULL, 'VISA COLOMBIA', 'United States', '(800) 396-9665', 'www.visa.com.co'),
    ('483103', 'VISA', 'DEBIT', 'INFINITE', 'BANCO NACIONAL DE COSTA RICA', 'COSTA RICA', '+50622112000', 'http://www.bnonline.fi.cr'),
    ('483104', 'VISA', 'DEBIT', 'GOLD', 'BANCO AZTECA S.A. INSTITUCION DE BANCA MULTIPLE', 'MEXICO', '+525554478810', 'https://www.bancoazteca.com.mx'),
    ('483105', 'VISA', 'DEBIT', NULL, 'UNIBANCA, S.A', 'United States', '507 297 6000', 'www.unibank.com.pa/'),
    ('483106', 'VISA', 'CREDIT', 'BUSINESS', 'BANCO DE RESERVAS DE LA REPUBLICA DOMINICANA', 'DOMINICAN REPUBLIC', '+18095490343', 'http://www.banreservas.com.do'),
    ('483107', 'VISA', 'DEBIT', 'GOLD', NULL, 'GUATEMALA', NULL, NULL),
    ('483108', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483109', 'VISA', 'DEBIT', NULL, 'VENTAS INTERNACIONALES, S.A. DE C.V.', 'United States', '+34 902 32 32 31', 'ventasinternacionales.com/en/'),
    ('483110', 'VISA', 'DEBIT', NULL, 'TARJETAS DE ORO S.A. DE C.V.', 'United States', NULL, NULL),
    ('483111', 'VISA', 'DEBIT', NULL, 'UNIBANCO - UNIAO DE BANCOS BRASILEIROS, S.A.', 'United States', '0800 728 0728', 'www.itau.com.br'),
    ('483112', 'VISA', 'DEBIT', 'CLASSIC', 'BANCO AZTECA S.A. INSTITUCION DE BANCA MULTIPLE', 'MEXICO', '+525554478810', 'https://www.bancoazteca.com.mx'),
    ('483113', 'VISA', 'DEBIT', NULL, 'WESTPAC BANKING CORPORATION', 'United States', '+1 212 551 1800', 'www.westpac.com.au'),
    ('483114', 'VISA', 'DEBIT', 'CLASSIC', 'BANCO SANTANDER, S.A.', 'URUGUAY', NULL, 'http://www.santander.com'),
    ('483115', 'VISA', 'CREDIT', 'PLATINUM', 'AL RAJHI BANKING AND INVESTMENT CORP.', 'SAUDI ARABIA', '4433 92 000 + 966 OR 33 334 601 +966', 'http://www.alrajhibank.com.sa'),
    ('483116', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483117', 'VISA', 'DEBIT', NULL, 'YES BANK, LTD.', 'United States', '+91 22 6121 9000', 'www.yesbank.in'),
    ('483118', 'VISA', 'DEBIT', NULL, 'YES BANK, LTD.', 'United States', '+91 22 6121 9000', 'www.yesbank.in'),
    ('483119', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483120', 'VISA', 'DEBIT', 'PREPAID CLASSIC', 'ECOBANK SOUTH SUDAN, LTD.', 'SOUTH SUDAN', NULL, NULL),
    ('483121', 'VISA', 'DEBIT', NULL, 'YES BANK, LTD.', 'United States', '+91 22 6121 9000', 'www.yesbank.in'),
    ('483122', 'VISA', 'DEBIT', NULL, 'TAMARA BANK', 'United States', NULL, NULL),
    ('483123', 'VISA', 'DEBIT', NULL, 'TAMARA BANK', 'United States', NULL, NULL),
    ('483124', 'VISA', 'DEBIT', NULL, 'TAMARA BANK', 'United States', NULL, NULL),
    ('483125', 'VISA', 'DEBIT', NULL, 'TAMARA BANK', 'United States', NULL, NULL),
    ('483126', 'VISA', 'CREDIT', 'PLATINUM', 'BANCO NACIONAL DE COSTA RICA', 'COSTA RICA', '+50622112000', 'http://www.bnonline.fi.cr'),
    ('483127', 'VISA', 'DEBIT', 'PREPAID CLASSIC', 'MELKAR PREPAID CARD NV', 'CURACAO', NULL, NULL),
    ('483128', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483129', 'VISA', 'DEBIT', NULL, 'MAURITIUS COMMERCIAL BANK LIMITED', 'United States', '+230 202 6060', 'www.mcb.mu/en/'),
    ('483130', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483131', 'VISA', 'DEBIT', 'CLASSIC', 'BANCO COMERCIAL E DE INVESTIMENTOS SARL', 'MOZAMBIQUE', '+25821353700', 'http://www.bci.co.mz'),
    ('483132', 'VISA', 'DEBIT', 'BUSINESS', 'UNIVERSAL MERCHANT BANK, LTD.', 'GHANA', NULL, NULL),
    ('483133', 'VISA', 'DEBIT', 'PREPAID CLASSIC', 'UNIVERSAL MERCHANT BANK, LTD.', 'GHANA', NULL, NULL),
    ('483134', 'VISA', 'DEBIT', 'PLATINUM', 'UNIVERSAL MERCHANT BANK, LTD.', 'GHANA', NULL, NULL),
    ('483135', 'VISA', 'DEBIT', NULL, 'YES BANK, LTD.', 'United States', '+91 22 6121 9000', 'www.yesbank.in'),
    ('483136', 'VISA', 'DEBIT', 'PLATINUM', 'AXIS BANK, LTD.', 'INDIA', '+912224252525', 'http://www.axisbank.com'),
    ('483137', 'VISA', 'CREDIT', 'REWARDS', 'LIMITED LIABILITY COMPANY OZON BANK', 'RUSSIAN FEDERATION', NULL, NULL);

INSERT OR REPLACE INTO bins (bin, brand, type, category, issuer, country, bank_phone, bank_url) VALUES
    ('483138', 'VISA', 'DEBIT', 'CLASSIC', 'E. SUN COMMERCIAL BANK, LTD.', 'TAIWAN, PROVINCE OF CHINA', NULL, NULL),
    ('483139', 'VISA', 'CREDIT', 'SIGNATURE', 'OVERSEA-CHINESE BANKING CORPORATION LTD.', 'SINGAPORE', NULL, NULL),
    ('483140', 'VISA', 'CREDIT', NULL, 'VISION BANCO SOCIEDAD ANONIMA EMISORA DECAPITAL ABIERTO', 'United States', '021 414 3000', 'www.visionbanco.com'),
    ('483141', 'VISA', 'CREDIT', NULL, 'WIRECARD BANK AG', 'United States', NULL, 'www.wirecard.us'),
    ('483142', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483143', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483144', 'VISA', 'CREDIT', 'ULTRA HIGH NET WORTH', 'SARADAR BANK SAL', 'LEBANON', NULL, NULL),
    ('483145', 'VISA', 'CREDIT', 'PLATINUM', 'DUTCH-BANGLA BANK, LTD.', 'BANGLADESH', NULL, 'http://www.dutchbanglabank.com'),
    ('483146', 'VISA', 'DEBIT', 'PREPAID CLASSIC', 'STATE BANK OF INDIA', 'BANGLADESH', '+88029563992', 'https://sbi.co.in'),
    ('483147', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483148', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483149', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483150', 'VISA', 'CREDIT', NULL, 'WIRECARD BANK AG', 'United States', NULL, 'www.wirecard.us'),
    ('483151', 'VISA', 'CREDIT', NULL, 'WIRECARD BANK AG', 'United States', NULL, 'www.wirecard.us'),
    ('483152', 'VISA', 'CREDIT', NULL, 'VISA ARGENTINA, S.A.', 'United States', '1-800-847-2911', 'www.visa.com.ar/'),
    ('483153', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483154', 'VISA', 'CREDIT', NULL, 'VISA ARGENTINA, S.A.', 'United States', '1-800-847-2911', 'www.visa.com.ar/'),
    ('483155', 'VISA', 'DEBIT', 'PREPAID', 'SCOTIA BANK', 'CANADA', NULL, NULL),
    ('483156', 'VISA', 'DEBIT', 'PREPAID PURCHASING', 'PEOPLES TRUST COMPANY', 'CANADA', '+16046832881', 'http://www.peoplestrust.com'),
    ('483157', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483158', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483159', 'VISA', 'DEBIT', 'CLASSIC', NULL, 'ARGENTINA', NULL, NULL),
    ('483160', 'VISA', 'CREDIT', NULL, 'VISA COLOMBIA', 'United States', '(800) 396-9665', 'www.visa.com.co'),
    ('483161', 'VISA', 'CREDIT', NULL, 'VISA COLOMBIA', 'United States', '(800) 396-9665', 'www.visa.com.co'),
    ('483162', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483163', 'VISA', 'DEBIT', 'PREPAID', NULL, 'UNITED ARAB EMIRATES', NULL, NULL),
    ('483164', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483165', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483166', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483167', 'VISA', 'DEBIT', 'PREPAID PLATINUM', 'IDFC FIRST BANK, LTD.', 'INDIA', NULL, NULL),
    ('483168', 'VISA', 'DEBIT', 'PREPAID CLASSIC', 'UNITED BANK FOR AFRICA BURKINA', 'BURKINA FASO', NULL, NULL),
    ('483169', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483170', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483171', 'VISA', 'CREDIT', NULL, 'VISA COLOMBIA', 'United States', '(800) 396-9665', 'www.visa.com.co'),
    ('483172', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483173', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483174', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483175', 'VISA', 'DEBIT', 'REWARDS', 'JSC RUSSIAN STANDARD BANK', 'RUSSIAN FEDERATION', NULL, 'http://www.rsb.ru'),
    ('483176', 'VISA', 'CREDIT', 'SIGNATURE', 'JSC RUSSIAN STANDARD BANK', 'RUSSIAN FEDERATION', NULL, 'http://www.rsb.ru'),
    ('483177', 'VISA', 'DEBIT', 'SIGNATURE', 'JSC RUSSIAN STANDARD BANK', 'RUSSIAN FEDERATION', NULL, 'http://www.rsb.ru'),
    ('483178', 'VISA', 'CREDIT', NULL, 'UNITED SAUDI COMMERCIAL BANK', 'United States', '(966) 1-4784200', NULL),
    ('483179', 'VISA', 'DEBIT', 'PREPAID CLASSIC', 'UNIBANCA, S.A.', 'PERU', NULL, NULL),
    ('483180', 'VISA', 'DEBIT', 'PREPAID CLASSIC', 'COOPERATIVA NACIONAL DE EDUCADORES R.L. (COOPENAE R.L.)', 'COSTA RICA', NULL, NULL),
    ('483181', 'VISA', 'CREDIT', NULL, 'TARJETA NARANJA DOMINICANA, S.A.', 'United States', '0810-333-6272', 'www.naranja.com'),
    ('483182', 'VISA', 'CREDIT', NULL, 'VISA ARGENTINA, S.A.', 'United States', '1-800-847-2911', 'www.visa.com.ar/'),
    ('483183', 'VISA', 'CREDIT', 'SIGNATURE', 'TD BANK USA NORDSTROM', 'PUERTO RICO', NULL, NULL),
    ('483184', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483185', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483186', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483187', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483188', 'VISA', 'DEBIT', NULL, 'VISA ARGENTINA, S.A.', 'United States', '1-800-847-2911', 'www.visa.com.ar/'),
    ('483189', 'VISA', 'CREDIT', 'GOLD', 'BANCO NACIONAL DE COSTA RICA', 'COSTA RICA', '+50622112000', 'http://www.bnonline.fi.cr'),
    ('483190', 'VISA', 'CREDIT', 'INFINITE', 'BANCO NACIONAL DE COSTA RICA', 'COSTA RICA', '+50622112000', 'http://www.bnonline.fi.cr'),
    ('483191', 'VISA', 'CREDIT', 'BUSINESS', 'U.S. REGION', 'UNITED STATES', NULL, NULL),
    ('483192', 'VISA', 'DEBIT', 'PLATINUM', 'AIB GROUP (UK) PLC', 'UNITED KINGDOM', '+448456005204', 'http://www.aibgb.co.uk'),
    ('483193', 'VISA', 'DEBIT', 'BUSINESS', 'SANTANDER UK PLC', 'UNITED KINGDOM', '+448003899905', 'http://www.santander.co.uk'),
    ('483194', 'VISA', 'DEBIT', 'BUSINESS', 'SANTANDER UK PLC', 'UNITED KINGDOM', '+448003899905', 'http://www.santander.co.uk'),
    ('483195', 'VISA', 'CREDIT', 'BUSINESS', 'CREDIT CORPORATION FINANCE, LTD.', 'PAPUA NEW GUINEA', NULL, NULL),
    ('483196', 'VISA', 'CREDIT', 'ULTRA HIGH NET WORTH', 'UNITED OVERSEAS BANK, LTD.', 'SINGAPORE', NULL, 'http://www.uob.com.sg'),
    ('483197', 'VISA', 'DEBIT', 'CLASSIC', 'BELLCO CREDIT UNION', 'UNITED STATES', '+13036897800', 'https://www.bellco.org'),
    ('483198', 'VISA', 'CREDIT', NULL, 'FISERV SOLUTIONS, LLC', 'UNITED STATES', '+18005649184', 'https://www.fiserv.com'),
    ('483199', 'VISA', 'CREDIT', NULL, 'FISERV CNS', 'United States', '800-554-8969', 'www.fiserv.com/'),
    ('483200', 'VISA', 'DEBIT', 'BUSINESS', 'BELLCO CREDIT UNION', 'UNITED STATES', '+13036897800', 'https://www.bellco.org'),
    ('483201', 'VISA', 'DEBIT', 'PREPAID CLASSIC', 'COMMERCE BANCSHARES, INC.', 'UNITED STATES', '+18556591656', 'https://www.commercebank.com'),
    ('483202', 'VISA', 'CREDIT', 'SIGNATURE', 'TRUST BANK, LTD.', 'BANGLADESH', NULL, 'http://www.trustbank.com.bd'),
    ('483203', 'VISA', 'DEBIT', 'INFINITE', 'ZENUS BANK INTERNATIONAL, INC', 'PUERTO RICO', NULL, NULL),
    ('483204', 'VISA', 'DEBIT', 'CLASSIC', 'LLOYDS BANK PLC', 'UNITED KINGDOM', '+448713842990', 'http://www.lloydsbankinggroup.com'),
    ('483205', 'VISA', 'DEBIT', 'CLASSIC', 'BANK OF SCOTLAND PLC', 'UNITED KINGDOM', '+441890818181 / +448007832824', 'http://www.bankofscotland.co.uk'),
    ('483206', 'VISA', 'DEBIT', 'CLASSIC', 'BANK OF SCOTLAND PLC', 'UNITED KINGDOM', '+441890818181 / +448007832824', 'http://www.bankofscotland.co.uk'),
    ('483207', 'VISA', 'DEBIT', 'CLASSIC', 'GEORGIA UNITED CREDIT UNION', 'UNITED STATES', '+17704766400', 'https://gucu.org'),
    ('483208', 'VISA', 'DEBIT', NULL, 'YORKSHIRE BANK', 'United States', '+44 141 951 7315', 'secure.ybonlane.co.uk'),
    ('483209', 'VISA', 'CREDIT', 'CLASSIC', 'NATIONWIDE BUILDING SOCIETY', 'UNITED KINGDOM', '+448000556611', 'http://www.nationwide.co.uk'),
    ('483210', 'VISA', 'CREDIT', NULL, 'YORKSHIRE BANK', 'United States', '+44 141 951 7315', 'secure.ybonlane.co.uk'),
    ('483211', 'VISA', 'DEBIT', 'CLASSIC', 'BANK OF SCOTLAND PLC', 'UNITED KINGDOM', '+441890818181 / +448007832824', 'http://www.bankofscotland.co.uk'),
    ('483212', 'VISA', 'CREDIT', 'TRADITIONAL', 'GENERATIONS COMMUNITY FEDERAL CREDIT UNION', 'UNITED STATES', NULL, NULL),
    ('483213', 'VISA', 'DEBIT', 'CLASSIC', 'GENERATIONS COMMUNITY FEDERAL CREDIT UNION', 'UNITED STATES', NULL, NULL),
    ('483214', 'VISA', 'DEBIT', 'CLASSIC', 'ROYAL BANK OF SCOTLAND PLC', 'UNITED KINGDOM', '+448001615153', 'http://www.rbs.co.uk'),
    ('483215', 'VISA', 'DEBIT', 'PLATINUM', 'HSBC BANK PLC', 'UNITED KINGDOM', NULL, 'http://www.hsbc.co.uk'),
    ('483216', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483217', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483218', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483219', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483220', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483221', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483222', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483223', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483224', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483225', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483226', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483227', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483228', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483229', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483230', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483231', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483232', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483233', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483234', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483235', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483236', 'VISA', 'CREDIT', NULL, 'CAPITAL ONE', 'United States', '1-800-227 4825', 'www.capitalane.com'),
    ('483237', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL);

INSERT OR REPLACE INTO bins (bin, brand, type, category, issuer, country, bank_phone, bank_url) VALUES
    ('483238', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483239', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483240', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483241', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483242', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483243', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483244', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483245', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483246', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483247', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483248', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483249', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483250', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483251', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483252', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483253', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483254', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483255', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483256', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483257', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483258', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483259', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483260', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483261', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483262', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483263', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483264', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483265', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483266', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483267', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483268', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483269', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483270', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483271', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483272', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483273', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483274', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483275', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483276', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483277', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483278', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483279', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483280', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483281', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483282', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483283', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483284', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483285', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483286', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483287', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483288', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483289', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483290', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483291', 'VISA', 'DEBIT', 'CLASSIC', 'CONVERSE BANK CORPORATION', 'ARMENIA', '(210) 659-5538', 'http://www.conversebank.am'),
    ('483292', 'VISA', 'DEBIT', NULL, 'ZHELDORBANK JSB', 'United States', NULL, NULL),
    ('483293', 'VISA', 'DEBIT', 'PREPAID PLATINUM', 'LIVQUIK TECHNOLOGY (INDIA) PRIVATE, LTD.', 'INDIA', NULL, NULL),
    ('483294', 'VISA', 'DEBIT', 'INFINITE', NULL, 'RUSSIAN FEDERATION', NULL, NULL),
    ('483295', 'VISA', 'CREDIT', 'SIGNATURE', 'CSCBANK SAL', 'LEBANON', NULL, NULL),
    ('483296', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483297', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483298', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483299', 'VISA', 'CREDIT', NULL, NULL, 'United States', NULL, NULL),
    ('483300', 'VISA', 'CREDIT', NULL, 'U.S. BANK N.A. ND', 'United States', '800.685.5065', 'www.usbank.com/'),
    ('483301', 'VISA', 'CREDIT', NULL, 'U.S. BANK N.A. ND', 'United States', '800.685.5065', 'www.usbank.com/'),
    ('483302', 'VISA', 'DEBIT', 'CLASSIC', 'PREMIER BANK', 'United States', '1-800-772-6497', 'www.premierbanks.com'),
    ('483303', 'VISA', 'DEBIT', 'BUSINESS', 'PREMIER BANK', 'United States', '1-800-772-6497', 'www.premierbanks.com'),
    ('483304', 'VISA', 'DEBIT', 'PREPAID CLASSIC', 'AXIOM BANK', 'UNITED STATES', '+18005840015', 'https://www.axiombanking.com'),
    ('483305', 'VISA', 'CREDIT', 'CLASSIC', 'POMELO TECH S.A. DE C.V.', 'MEXICO', NULL, NULL),
    ('483306', 'VISA', 'DEBIT', 'CLASSIC', 'HOLSTON METHODIST F.C.U.', 'United States', '(865) 558-3117', 'http://hmfcu.org/'),
    ('483307', 'VISA', 'DEBIT', 'PREPAID', 'U.S. BANK, N.A.', 'United States', NULL, NULL),
    ('483308', 'VISA', 'CREDIT', NULL, 'U.S. BANK, N.A.', 'UNITED STATES', '+18008722657', 'https://www.usbank.com'),
    ('483309', 'VISA', 'CREDIT', NULL, 'U.S. BANK, N.A.', 'UNITED STATES', '+18008722657', 'https://www.usbank.com'),
    ('483310', 'VISA', 'CREDIT', 'TRADITIONAL', 'MRV BANKS', 'UNITED STATES', '+15738838222', 'https://www.mrvbanks.com'),
    ('483311', 'VISA', 'DEBIT', 'PREPAID CORPORATE T&E', 'THOMAS COOK (INDIA), LTD.', 'INDIA', NULL, NULL),
    ('483312', 'VISA', 'DEBIT', 'CLASSIC', 'U.S. BANK, N.A.', 'United States', NULL, NULL),
    ('483313', 'VISA', 'DEBIT', 'CLASSIC', 'JPMORGAN CHASE BANK N.A. - DEBIT', 'UNITED STATES', NULL, NULL),
    ('483314', 'VISA', 'DEBIT', 'CLASSIC', 'JPMORGAN CHASE BANK N.A. - DEBIT', 'UNITED STATES', NULL, NULL),
    ('483315', 'VISA', 'DEBIT', 'CLASSIC', 'U.S. BANK, N.A.', 'UNITED STATES', '+18008722657', 'https://www.usbank.com'),
    ('483316', 'VISA', 'DEBIT', 'CLASSIC', 'JPMORGAN CHASE BANK N.A. - DEBIT', 'UNITED STATES', NULL, NULL),
    ('483317', 'VISA', 'DEBIT', 'PREPAID', 'U.S. BANK, N.A.', 'United States', NULL, NULL),
    ('483318', 'VISA', 'DEBIT', 'PREPAID', 'METABANK', 'United States', '1.866.559.5037', 'www.metabank.com'),
    ('483319', 'VISA', 'CREDIT', 'CLASSIC', 'METABANK', 'United States', '1.866.559.5037', 'www.metabank.com'),
    ('483320', 'VISA', 'DEBIT', 'CLASSIC', 'U.S. BANK, N.A.', 'United States', NULL, NULL),
    ('483321', 'VISA', 'DEBIT', 'BUSINESS', 'U.S. BANK, N.A.', 'United States', NULL, NULL),
    ('483322', 'VISA', 'DEBIT', 'PREPAID', 'U.S. BANK, N.A.', 'UNITED STATES', '+18008722657', 'https://www.usbank.com'),
    ('483323', 'VISA', 'DEBIT', 'PREPAID', 'CHASE BANK USA, N.A.', 'UNITED STATES', '+18009359935', 'http://www.chase.com'),
    ('483324', 'VISA', 'DEBIT', 'PREPAID', 'CHASE BANK USA, N.A.', 'UNITED STATES', '+18009359935', 'http://www.chase.com'),
    ('483325', 'VISA', 'DEBIT', 'PREPAID', 'U.S. BANK, N.A.', 'UNITED STATES', '+18008722657', 'https://www.usbank.com'),
    ('483326', 'VISA', 'DEBIT', 'PREPAID', 'U.S. BANK, N.A.', 'United States', NULL, NULL),
    ('483327', 'VISA', 'DEBIT', 'PREPAID', 'U.S. BANK, N.A.', 'UNITED STATES', '+18008722657', 'https://www.usbank.com'),
    ('483328', 'VISA', 'CREDIT', 'CLASSIC', 'U.S. BANK, N.A.', 'UNITED STATES', '+18008722657', 'https://www.usbank.com'),
    ('483329', 'VISA', 'DEBIT', 'CLASSIC', 'ZENITH BANK (GHANA), LTD.', 'GHANA', NULL, NULL),
    ('483330', 'VISA', 'CREDIT', NULL, 'U.S. BANK, N.A.', 'UNITED STATES', '+18008722657', 'https://www.usbank.com'),
    ('483331', 'VISA', 'DEBIT', 'CLASSIC', 'U.S. BANK, N.A.', 'United States', NULL, NULL),
    ('483332', 'VISA', 'DEBIT', 'CLASSIC', 'GULF WINDS CREDIT UNION', 'UNITED STATES', '+18006506328', 'https://www.gogulfwinds.com'),
    ('483333', 'VISA', 'DEBIT', 'CLASSIC', 'U.S. BANK, N.A.', 'UNITED STATES', '+18008722657', 'https://www.usbank.com'),
    ('483334', 'VISA', 'CREDIT', 'CLASSIC', 'DEUTSCHE BANK AG', 'GERMANY', '+4939026995', 'https://www.db.com'),
    ('483335', 'VISA', 'CREDIT', 'PLATINUM', 'ISRACARD, LTD.', 'ISRAEL', NULL, NULL),
    ('483336', 'VISA', 'CREDIT', NULL, 'U.S. BANK, N.A.', 'UNITED STATES', '+18008722657', 'https://www.usbank.com'),
    ('483337', 'VISA', 'CREDIT', NULL, 'U.S. BANK, N.A.', 'UNITED STATES', '+18008722657', 'https://www.usbank.com');

COMMIT;
