-- Batch 625 - 500 records
BEGIN TRANSACTION;

INSERT OR REPLACE INTO bins (bin, brand, type, category, issuer, country, bank_phone, bank_url) VALUES
    ('577338', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577339', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577340', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577341', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577342', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577343', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577344', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577345', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577346', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577347', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577348', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577349', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'UNITED KINGDOM', NULL, NULL),
    ('577350', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577351', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577352', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577353', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577354', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577355', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577356', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577357', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577358', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577359', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577360', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577361', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577362', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577363', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577364', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577365', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577366', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577367', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577368', 'EBT', 'DEBIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('577369', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577370', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577371', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577372', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577373', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577374', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577375', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577376', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577377', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577378', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577379', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577380', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577381', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577382', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577383', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577384', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577385', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577386', 'CIRRUS', 'DEBIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('577387', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577388', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577389', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577390', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577391', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577392', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577393', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577394', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577395', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577396', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577397', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577398', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577399', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577400', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577401', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577402', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577403', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577404', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577405', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577406', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577407', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577408', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577409', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577410', 'CIRRUS', 'DEBIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('577411', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577412', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'MEXICO', NULL, NULL),
    ('577413', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577414', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577415', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577416', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577417', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577418', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577419', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577420', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577421', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577422', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577423', 'EBT', 'DEBIT', 'PERSONAL', 'BMO HARRIS BANK, N.A.', 'UNITED STATES', '+18883402265', 'https://www.bmoharris.com'),
    ('577424', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577425', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577426', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577427', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577428', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577429', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577430', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577431', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577432', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577433', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577434', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577435', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577436', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577437', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL);

INSERT OR REPLACE INTO bins (bin, brand, type, category, issuer, country, bank_phone, bank_url) VALUES
    ('577438', 'MAESTRO', 'DEBIT', 'STANDARD', 'MAESTRO INTERNATIONAL', 'GAMBIA', NULL, 'https://brand.mastercard.com'),
    ('577439', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577440', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577441', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577442', 'CIRRUS', 'DEBIT', NULL, 'BEST BUY', 'UNITED STATES', NULL, NULL),
    ('577443', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577444', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577445', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577446', 'MAESTRO', 'DEBIT', 'STANDARD', 'MAESTRO INTERNATIONAL', 'SPAIN', '+34902100234', 'https://brand.mastercard.com'),
    ('577447', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577448', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577449', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577450', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577451', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577452', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577453', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577454', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577455', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577456', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577457', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577458', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577459', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577460', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577461', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577462', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577463', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577464', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577465', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577466', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577467', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577468', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577469', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577470', 'EBT', 'DEBIT', 'PERSONAL', NULL, 'UNITED STATES', NULL, NULL),
    ('577471', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577472', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577473', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577474', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577475', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577476', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577477', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577478', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577479', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577480', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577481', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577482', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577483', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577484', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577485', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577486', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577487', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577488', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577489', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577490', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577491', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577492', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577493', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577494', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577495', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577496', 'MAESTRO', 'DEBIT', 'STANDARD', 'MAESTRO INTERNATIONAL', 'BRAZIL', NULL, 'https://brand.mastercard.com'),
    ('577497', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577498', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577499', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577500', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577501', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577502', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577503', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577504', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577505', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577506', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577507', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577508', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577509', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577510', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577511', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577512', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577513', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577514', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577515', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577516', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577517', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577518', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577519', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577520', 'MAESTRO', 'DEBIT', 'STANDARD', 'MAESTRO INTERNATIONAL', 'COLOMBIA', NULL, 'https://brand.mastercard.com'),
    ('577521', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577522', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577523', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577524', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577525', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577526', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577527', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577528', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577529', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577530', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577531', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577532', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577533', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577534', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577535', 'CIRRUS', 'DEBIT', 'PERSONAL', NULL, 'UNITED STATES', NULL, NULL),
    ('577536', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577537', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL);

INSERT OR REPLACE INTO bins (bin, brand, type, category, issuer, country, bank_phone, bank_url) VALUES
    ('577538', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577539', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577540', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577541', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577542', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577543', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577544', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577545', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577546', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577547', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577548', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577549', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577550', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577551', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577552', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577553', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577554', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577555', 'CIRRUS', 'DEBIT', 'PERSONAL', NULL, 'UNITED STATES', NULL, NULL),
    ('577556', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577557', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577558', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577559', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577560', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577561', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577562', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577563', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577564', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577565', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577566', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577567', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577568', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577569', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577570', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577571', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577572', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577573', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577574', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577575', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577576', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577577', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577578', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577579', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577580', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577581', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577582', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577583', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577584', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577585', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577586', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577587', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577588', 'MAESTRO', 'DEBIT', 'STANDARD', 'MAESTRO INTERNATIONAL', 'INDIA', NULL, 'https://brand.mastercard.com'),
    ('577589', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577590', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577591', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577592', 'EBT', 'DEBIT', 'PERSONAL', NULL, 'UNITED STATES', NULL, NULL),
    ('577593', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577594', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577595', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577596', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577597', 'MAESTRO', 'DEBIT', 'STANDARD', 'MAESTRO INTERNATIONAL', 'MOROCCO', NULL, 'https://brand.mastercard.com'),
    ('577598', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577599', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577600', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577601', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577602', 'CIRRUS', 'DEBIT', 'PERSONAL', NULL, 'UNITED STATES', NULL, NULL),
    ('577603', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577604', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577605', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577606', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577607', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577608', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577609', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577610', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577611', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577612', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577613', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577614', 'CIRRUS', 'DEBIT', 'PERSONAL', NULL, 'UNITED STATES', NULL, NULL),
    ('577615', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577616', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577617', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577618', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577619', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577620', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577621', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577622', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577623', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577624', 'EBT', 'DEBIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('577625', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577626', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577627', 'EBT', 'DEBIT', 'PERSONAL', NULL, 'UNITED STATES', NULL, NULL),
    ('577628', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577629', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577630', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577631', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577632', 'MAESTRO', 'DEBIT', 'STANDARD', 'MAESTRO INTERNATIONAL', 'BRAZIL', NULL, 'https://brand.mastercard.com'),
    ('577633', 'CIRRUS', 'DEBIT', 'PERSONAL', NULL, 'UNITED STATES', NULL, NULL),
    ('577634', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577635', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577636', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577637', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL);

INSERT OR REPLACE INTO bins (bin, brand, type, category, issuer, country, bank_phone, bank_url) VALUES
    ('577638', 'MAESTRO', 'DEBIT', 'STANDARD', 'MAESTRO INTERNATIONAL', 'SPAIN', '+34902100234', 'https://brand.mastercard.com'),
    ('577639', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577640', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577641', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577642', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577643', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577644', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577645', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577646', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577647', 'CIRRUS', 'DEBIT', 'PERSONAL', NULL, 'UNITED STATES', NULL, NULL),
    ('577648', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577649', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577650', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577651', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577652', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577653', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577654', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577655', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577656', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577657', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577658', 'CIRRUS', 'DEBIT', NULL, NULL, 'UNITED STATES', NULL, NULL),
    ('577659', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577660', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577661', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577662', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577663', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577664', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577665', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577666', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577667', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577668', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577669', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577670', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577671', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577672', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577673', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577674', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577675', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577676', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577677', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577678', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577679', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577680', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577681', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577682', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577683', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577684', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577685', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577686', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577687', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577688', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577689', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577690', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577691', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577692', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577693', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577694', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577695', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577696', 'CIRRUS', 'DEBIT', 'PERSONAL', NULL, 'UNITED STATES', NULL, NULL),
    ('577697', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577698', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577699', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577700', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577701', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577702', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577703', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577704', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577705', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577706', 'MAESTRO', 'DEBIT', 'STANDARD', 'MAESTRO INTERNATIONAL', 'ITALY', '+39800870866', 'https://brand.mastercard.com'),
    ('577707', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577708', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577709', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577710', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'TAIWAN, PROVINCE OF CHINA', NULL, NULL),
    ('577711', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577712', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577713', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577714', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577715', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577716', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577717', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577718', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577719', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577720', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577721', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577722', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577723', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577724', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577725', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577726', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577727', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577728', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577729', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577730', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577731', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577732', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577733', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577734', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577735', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577736', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577737', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'MOROCCO', NULL, NULL);

INSERT OR REPLACE INTO bins (bin, brand, type, category, issuer, country, bank_phone, bank_url) VALUES
    ('577738', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577739', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577740', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577741', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577742', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577743', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577744', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577745', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577746', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577747', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577748', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577749', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577750', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577751', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577752', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577753', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577754', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577755', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577756', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577757', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'MOROCCO', NULL, NULL),
    ('577758', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577759', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577760', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577761', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577762', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577763', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577764', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577765', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577766', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577767', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577768', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577769', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577770', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'JAMAICA', NULL, NULL),
    ('577771', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577772', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577773', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577774', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577775', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577776', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577777', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577778', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577779', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577780', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577781', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577782', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577783', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577784', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577785', 'EBT', 'DEBIT', 'STANDARD', 'U.S. BANK, N.A.', 'UNITED STATES', '+18008722657', 'https://www.usbank.com'),
    ('577786', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577787', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577788', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577789', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577790', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577791', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577792', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577793', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577794', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577795', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577796', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577797', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577798', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577799', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577800', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577801', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577802', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577803', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577804', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577805', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'TURKEY', NULL, NULL),
    ('577806', 'EBT', 'DEBIT', NULL, 'SHAZAM, INC.', 'UNITED STATES', '+18005375427', 'http://www.shazam.net'),
    ('577807', 'MAESTRO', 'DEBIT', 'STANDARD', 'MAESTRO INTERNATIONAL', 'FRANCE', '+33800901387', 'https://brand.mastercard.com'),
    ('577808', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577809', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577810', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577811', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577812', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577813', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577814', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577815', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577816', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577817', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577818', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577819', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577820', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577821', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577822', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577823', 'MAESTRO', 'DEBIT', NULL, NULL, 'United States', NULL, NULL),
    ('577824', 'EBT', 'DEBIT', 'STANDARD', 'MAESTRO INTERNATIONAL', 'UNITED STATES', NULL, 'https://brand.mastercard.com'),
    ('577825', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577826', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577827', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577828', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577829', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577830', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577831', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577832', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577833', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577834', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL),
    ('577835', 'CIRRUS', 'DEBIT', 'PERSONAL', NULL, 'UNITED STATES', NULL, NULL),
    ('577836', 'MAESTRO', 'DEBIT', NULL, NULL, NULL, NULL, NULL),
    ('577837', 'MAESTRO', 'DEBIT', 'STANDARD', NULL, 'United States', NULL, NULL);

COMMIT;
